//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACMTJ
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TJ001 { get; set; }
        public string TJ002 { get; set; }
        public string TJ003 { get; set; }
        public Nullable<decimal> TJ004 { get; set; }
        public Nullable<decimal> TJ005 { get; set; }
        public string TJ006 { get; set; }
        public Nullable<decimal> TJ007 { get; set; }
        public Nullable<decimal> TJ008 { get; set; }
        public Nullable<decimal> TJ009 { get; set; }
        public Nullable<decimal> TJ010 { get; set; }
        public Nullable<decimal> TJ011 { get; set; }
        public Nullable<decimal> TJ012 { get; set; }
        public Nullable<decimal> TJ013 { get; set; }
        public Nullable<decimal> TJ014 { get; set; }
        public Nullable<decimal> TJ015 { get; set; }
        public Nullable<decimal> TJ016 { get; set; }
        public Nullable<decimal> TJ017 { get; set; }
        public Nullable<decimal> TJ018 { get; set; }
        public Nullable<decimal> TJ019 { get; set; }
        public Nullable<decimal> TJ020 { get; set; }
        public Nullable<decimal> TJ021 { get; set; }
        public Nullable<decimal> TJ022 { get; set; }
        public Nullable<decimal> TJ023 { get; set; }
        public Nullable<decimal> TJ024 { get; set; }
        public string TJ025 { get; set; }
        public string TJ026 { get; set; }
        public string TJ027 { get; set; }
        public string TJ028 { get; set; }
        public string TJ029 { get; set; }
        public Nullable<decimal> TJ030 { get; set; }
        public Nullable<decimal> TJ031 { get; set; }
        public Nullable<decimal> TJ032 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
