//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACPTC
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TC001 { get; set; }
        public string TC002 { get; set; }
        public string TC003 { get; set; }
        public string TC004 { get; set; }
        public string TC005 { get; set; }
        public Nullable<decimal> TC006 { get; set; }
        public string TC007 { get; set; }
        public string TC008 { get; set; }
        public string TC009 { get; set; }
        public string TC010 { get; set; }
        public Nullable<decimal> TC011 { get; set; }
        public Nullable<decimal> TC012 { get; set; }
        public Nullable<decimal> TC013 { get; set; }
        public Nullable<decimal> TC014 { get; set; }
        public string TC015 { get; set; }
        public string TC016 { get; set; }
        public string TC017 { get; set; }
        public string TC018 { get; set; }
        public string TC019 { get; set; }
        public string TC020 { get; set; }
        public Nullable<decimal> TC021 { get; set; }
        public string TC022 { get; set; }
        public string TC023 { get; set; }
        public string TC024 { get; set; }
        public Nullable<decimal> TC025 { get; set; }
        public Nullable<decimal> TC026 { get; set; }
        public Nullable<decimal> TC027 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
