//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACRTA
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TA001 { get; set; }
        public string TA002 { get; set; }
        public string TA003 { get; set; }
        public string TA004 { get; set; }
        public string TA005 { get; set; }
        public string TA006 { get; set; }
        public string TA007 { get; set; }
        public string TA008 { get; set; }
        public string TA009 { get; set; }
        public Nullable<decimal> TA010 { get; set; }
        public string TA011 { get; set; }
        public string TA012 { get; set; }
        public string TA013 { get; set; }
        public string TA014 { get; set; }
        public string TA015 { get; set; }
        public string TA016 { get; set; }
        public Nullable<decimal> TA017 { get; set; }
        public Nullable<decimal> TA018 { get; set; }
        public string TA019 { get; set; }
        public string TA020 { get; set; }
        public string TA021 { get; set; }
        public string TA022 { get; set; }
        public string TA023 { get; set; }
        public string TA024 { get; set; }
        public string TA025 { get; set; }
        public string TA026 { get; set; }
        public string TA027 { get; set; }
        public Nullable<decimal> TA028 { get; set; }
        public Nullable<decimal> TA029 { get; set; }
        public Nullable<decimal> TA030 { get; set; }
        public Nullable<decimal> TA031 { get; set; }
        public string TA032 { get; set; }
        public string TA033 { get; set; }
        public Nullable<decimal> TA034 { get; set; }
        public string TA035 { get; set; }
        public string TA036 { get; set; }
        public Nullable<decimal> TA037 { get; set; }
        public string TA038 { get; set; }
        public string TA039 { get; set; }
        public Nullable<decimal> TA040 { get; set; }
        public Nullable<decimal> TA041 { get; set; }
        public Nullable<decimal> TA042 { get; set; }
        public string TA043 { get; set; }
        public string TA044 { get; set; }
        public string TA045 { get; set; }
        public Nullable<decimal> TA046 { get; set; }
        public Nullable<decimal> TA047 { get; set; }
        public string TA048 { get; set; }
        public string TA049 { get; set; }
        public string TA050 { get; set; }
        public string TA051 { get; set; }
        public string TA052 { get; set; }
        public string TA053 { get; set; }
        public string TA056 { get; set; }
        public string TA057 { get; set; }
        public Nullable<decimal> TA058 { get; set; }
        public Nullable<decimal> TA059 { get; set; }
        public Nullable<decimal> TA060 { get; set; }
        public string TA070 { get; set; }
        public string TA073 { get; set; }
        public string TA074 { get; set; }
        public string TA075 { get; set; }
        public Nullable<decimal> TA076 { get; set; }
        public Nullable<decimal> TA077 { get; set; }
        public Nullable<decimal> TA078 { get; set; }
        public string TA079 { get; set; }
        public string TA080 { get; set; }
        public string TA081 { get; set; }
        public string TA082 { get; set; }
        public string TA083 { get; set; }
        public string TA084 { get; set; }
        public string TA085 { get; set; }
        public string TA086 { get; set; }
        public string TA087 { get; set; }
        public string TA088 { get; set; }
        public string TA089 { get; set; }
        public string TA090 { get; set; }
        public string TA091 { get; set; }
        public string TA092 { get; set; }
        public string TA093 { get; set; }
        public string TA094 { get; set; }
        public string TA095 { get; set; }
        public string TA096 { get; set; }
        public string TA097 { get; set; }
        public Nullable<decimal> TA098 { get; set; }
        public Nullable<decimal> TA099 { get; set; }
        public string TA100 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
