//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACRTL
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TL001 { get; set; }
        public string TL002 { get; set; }
        public string TL003 { get; set; }
        public string TL004 { get; set; }
        public string TL005 { get; set; }
        public string TL006 { get; set; }
        public string TL007 { get; set; }
        public string TL008 { get; set; }
        public string TL009 { get; set; }
        public string TL010 { get; set; }
        public string TL011 { get; set; }
        public string TL012 { get; set; }
        public string TL013 { get; set; }
        public Nullable<decimal> TL014 { get; set; }
        public string TL015 { get; set; }
        public string TL016 { get; set; }
        public Nullable<decimal> TL017 { get; set; }
        public Nullable<decimal> TL018 { get; set; }
        public Nullable<decimal> TL019 { get; set; }
        public Nullable<decimal> TL020 { get; set; }
        public Nullable<decimal> TL021 { get; set; }
        public Nullable<decimal> TL022 { get; set; }
        public string TL023 { get; set; }
        public string TL024 { get; set; }
        public string TL025 { get; set; }
        public string TL026 { get; set; }
        public string TL027 { get; set; }
        public string TL028 { get; set; }
        public string TL029 { get; set; }
        public string TL030 { get; set; }
        public string TL031 { get; set; }
        public Nullable<decimal> TL032 { get; set; }
        public Nullable<decimal> TL033 { get; set; }
        public Nullable<decimal> TL034 { get; set; }
        public Nullable<decimal> TL035 { get; set; }
        public Nullable<decimal> TL036 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
