//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTMN
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MN001 { get; set; }
        public string MN002 { get; set; }
        public string MN003 { get; set; }
        public string MN004 { get; set; }
        public string MN005 { get; set; }
        public string MN006 { get; set; }
        public string MN007 { get; set; }
        public Nullable<decimal> MN008 { get; set; }
        public Nullable<decimal> MN009 { get; set; }
        public string MN010 { get; set; }
        public string MN011 { get; set; }
        public string MN012 { get; set; }
        public Nullable<decimal> MN013 { get; set; }
        public Nullable<decimal> MN014 { get; set; }
        public string MN015 { get; set; }
        public Nullable<decimal> MN016 { get; set; }
        public Nullable<decimal> MN017 { get; set; }
        public Nullable<decimal> MN018 { get; set; }
        public Nullable<decimal> MN019 { get; set; }
        public Nullable<decimal> MN020 { get; set; }
        public string MN021 { get; set; }
        public string MN022 { get; set; }
        public string MN023 { get; set; }
        public string MN024 { get; set; }
        public string MN025 { get; set; }
        public Nullable<decimal> MN026 { get; set; }
        public Nullable<decimal> MN027 { get; set; }
        public Nullable<decimal> MN028 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
