//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTMO
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MO001 { get; set; }
        public string MO002 { get; set; }
        public string MO003 { get; set; }
        public string MO004 { get; set; }
        public string MO005 { get; set; }
        public string MO006 { get; set; }
        public string MO007 { get; set; }
        public string MO008 { get; set; }
        public string MO009 { get; set; }
        public string MO010 { get; set; }
        public Nullable<decimal> MO011 { get; set; }
        public Nullable<decimal> MO012 { get; set; }
        public string MO013 { get; set; }
        public string MO014 { get; set; }
        public string MO015 { get; set; }
        public string MO016 { get; set; }
        public string MO017 { get; set; }
        public string MO018 { get; set; }
        public string MO019 { get; set; }
        public Nullable<decimal> MO020 { get; set; }
        public Nullable<decimal> MO021 { get; set; }
        public Nullable<decimal> MO022 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
