//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTMA
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MA001 { get; set; }
        public string MA002 { get; set; }
        public string MA003 { get; set; }
        public string MA004 { get; set; }
        public string MA005 { get; set; }
        public string MA006 { get; set; }
        public Nullable<decimal> MA007 { get; set; }
        public string MA008 { get; set; }
        public string MA009 { get; set; }
        public string MA010 { get; set; }
        public string MA011 { get; set; }
        public string MA012 { get; set; }
        public string MA013 { get; set; }
        public string MA014 { get; set; }
        public string MA015 { get; set; }
        public string MA016 { get; set; }
        public string MA017 { get; set; }
        public string MA018 { get; set; }
        public Nullable<decimal> MA019 { get; set; }
        public string MA020 { get; set; }
        public string MA021 { get; set; }
        public Nullable<decimal> MA022 { get; set; }
        public string MA023 { get; set; }
        public string MA024 { get; set; }
        public string MA025 { get; set; }
        public string MA026 { get; set; }
        public string MA027 { get; set; }
        public string MA028 { get; set; }
        public string MA029 { get; set; }
        public string MA030 { get; set; }
        public string MA031 { get; set; }
        public string MA032 { get; set; }
        public string MA033 { get; set; }
        public string MA034 { get; set; }
        public Nullable<decimal> MA035 { get; set; }
        public Nullable<decimal> MA036 { get; set; }
        public Nullable<decimal> MA037 { get; set; }
        public string MA038 { get; set; }
        public string MA039 { get; set; }
        public string MA040 { get; set; }
        public string MA041 { get; set; }
        public string MA042 { get; set; }
        public string MA043 { get; set; }
        public string MA044 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
