//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AJSLC
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string LC001 { get; set; }
        public string LC002 { get; set; }
        public string LC003 { get; set; }
        public string LC004 { get; set; }
        public string LC005 { get; set; }
        public string LC006 { get; set; }
        public string LC007 { get; set; }
        public string LC008 { get; set; }
        public string LC009 { get; set; }
        public Nullable<decimal> LC010 { get; set; }
        public Nullable<decimal> LC011 { get; set; }
        public string LC012 { get; set; }
        public string LC013 { get; set; }
        public string LC014 { get; set; }
        public string LC015 { get; set; }
        public Nullable<decimal> LC016 { get; set; }
        public Nullable<decimal> LC017 { get; set; }
        public Nullable<decimal> LC018 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
