//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMSMB
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MB001 { get; set; }
        public string MB002 { get; set; }
        public string MB003 { get; set; }
        public string MB004 { get; set; }
        public string MB005 { get; set; }
        public string MB006 { get; set; }
        public string MB007 { get; set; }
        public string MB008 { get; set; }
        public string MB009 { get; set; }
        public string MB010 { get; set; }
        public string MB011 { get; set; }
        public string MB012 { get; set; }
        public string MB013 { get; set; }
        public string MB014 { get; set; }
        public string MB015 { get; set; }
        public string MB016 { get; set; }
        public string MB017 { get; set; }
        public string MB018 { get; set; }
        public string MB019 { get; set; }
        public string MB020 { get; set; }
        public string MB021 { get; set; }
        public string MB022 { get; set; }
        public string MB023 { get; set; }
        public string MB024 { get; set; }
        public string MB025 { get; set; }
        public string MB026 { get; set; }
        public string MB027 { get; set; }
        public string MB028 { get; set; }
        public string MB029 { get; set; }
        public string MB030 { get; set; }
        public string MB031 { get; set; }
        public string MB032 { get; set; }
        public string MB033 { get; set; }
        public string MB034 { get; set; }
        public string MB035 { get; set; }
        public string MB036 { get; set; }
        public string MB037 { get; set; }
        public string MB038 { get; set; }
        public string MB039 { get; set; }
        public string MB040 { get; set; }
        public string MB041 { get; set; }
        public string MB042 { get; set; }
        public string MB043 { get; set; }
        public string MB044 { get; set; }
        public string MB045 { get; set; }
        public string MB046 { get; set; }
        public string MB047 { get; set; }
        public string MB048 { get; set; }
        public string MB049 { get; set; }
        public string MB050 { get; set; }
        public string MB051 { get; set; }
        public string MB052 { get; set; }
        public string MB053 { get; set; }
        public string MB054 { get; set; }
        public string MB055 { get; set; }
        public string MB056 { get; set; }
        public string MB057 { get; set; }
        public string MB058 { get; set; }
        public string MB059 { get; set; }
        public string MB060 { get; set; }
        public string MB061 { get; set; }
        public string MB062 { get; set; }
        public string MB063 { get; set; }
        public string MB064 { get; set; }
        public string MB065 { get; set; }
        public string MB066 { get; set; }
        public string MB067 { get; set; }
        public Nullable<decimal> MB068 { get; set; }
        public Nullable<decimal> MB069 { get; set; }
        public Nullable<decimal> MB070 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
