//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASTMA
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MA001 { get; set; }
        public string MA002 { get; set; }
        public string MA003 { get; set; }
        public string MA004 { get; set; }
        public string MA005 { get; set; }
        public string MA006 { get; set; }
        public Nullable<decimal> MA007 { get; set; }
        public string MA008 { get; set; }
        public Nullable<decimal> MA009 { get; set; }
        public Nullable<decimal> MA010 { get; set; }
        public string MA011 { get; set; }
        public string MA012 { get; set; }
        public string MA013 { get; set; }
        public string MA014 { get; set; }
        public Nullable<decimal> MA015 { get; set; }
        public Nullable<decimal> MA016 { get; set; }
        public Nullable<decimal> MA017 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
