//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASTTC
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TC001 { get; set; }
        public string TC002 { get; set; }
        public string TC003 { get; set; }
        public string TC004 { get; set; }
        public Nullable<decimal> TC005 { get; set; }
        public Nullable<decimal> TC006 { get; set; }
        public Nullable<decimal> TC007 { get; set; }
        public Nullable<decimal> TC008 { get; set; }
        public Nullable<decimal> TC009 { get; set; }
        public Nullable<decimal> TC010 { get; set; }
        public string TC011 { get; set; }
        public string TC012 { get; set; }
        public string TC013 { get; set; }
        public string TC014 { get; set; }
        public string TC015 { get; set; }
        public Nullable<decimal> TC016 { get; set; }
        public string TC017 { get; set; }
        public string TC018 { get; set; }
        public string TC019 { get; set; }
        public Nullable<decimal> TC020 { get; set; }
        public Nullable<decimal> TC021 { get; set; }
        public Nullable<decimal> TC022 { get; set; }
        public string TC023 { get; set; }
        public string TC024 { get; set; }
        public string TC025 { get; set; }
        public string TC026 { get; set; }
        public string TC027 { get; set; }
        public string TC028 { get; set; }
        public Nullable<decimal> TC029 { get; set; }
        public Nullable<decimal> TC030 { get; set; }
        public string TC031 { get; set; }
        public string TC032 { get; set; }
        public Nullable<decimal> TC033 { get; set; }
        public Nullable<decimal> TC034 { get; set; }
        public Nullable<decimal> TC035 { get; set; }
        public Nullable<decimal> TC036 { get; set; }
        public Nullable<decimal> TC037 { get; set; }
        public Nullable<decimal> TC038 { get; set; }
        public string TC039 { get; set; }
        public string TC040 { get; set; }
        public string TC041 { get; set; }
        public Nullable<decimal> TC042 { get; set; }
        public Nullable<decimal> TC043 { get; set; }
        public Nullable<decimal> TC044 { get; set; }
        public string TC045 { get; set; }
        public string TC046 { get; set; }
        public string TC047 { get; set; }
        public Nullable<decimal> TC048 { get; set; }
        public Nullable<decimal> TC049 { get; set; }
        public Nullable<decimal> TC050 { get; set; }
        public Nullable<decimal> TC051 { get; set; }
        public Nullable<decimal> TC052 { get; set; }
        public Nullable<decimal> TC053 { get; set; }
        public Nullable<decimal> TC054 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
