//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASTTP
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TP001 { get; set; }
        public string TP002 { get; set; }
        public string TP003 { get; set; }
        public string TP004 { get; set; }
        public string TP005 { get; set; }
        public string TP006 { get; set; }
        public Nullable<decimal> TP007 { get; set; }
        public string TP008 { get; set; }
        public string TP009 { get; set; }
        public string TP010 { get; set; }
        public string TP011 { get; set; }
        public string TP012 { get; set; }
        public Nullable<decimal> TP013 { get; set; }
        public Nullable<decimal> TP014 { get; set; }
        public Nullable<decimal> TP015 { get; set; }
        public Nullable<decimal> TP016 { get; set; }
        public Nullable<decimal> TP017 { get; set; }
        public Nullable<decimal> TP018 { get; set; }
        public Nullable<decimal> TP019 { get; set; }
        public string TP020 { get; set; }
        public string TP021 { get; set; }
        public string TP022 { get; set; }
        public string TP023 { get; set; }
        public string TP024 { get; set; }
        public string TP025 { get; set; }
        public string TP026 { get; set; }
        public string TP027 { get; set; }
        public string TP028 { get; set; }
        public string TP029 { get; set; }
        public string TP030 { get; set; }
        public string TP031 { get; set; }
        public string TP032 { get; set; }
        public string TP033 { get; set; }
        public string TP034 { get; set; }
        public Nullable<decimal> TP035 { get; set; }
        public Nullable<decimal> TP036 { get; set; }
        public Nullable<decimal> TP037 { get; set; }
        public Nullable<decimal> TP038 { get; set; }
        public string TP039 { get; set; }
        public Nullable<decimal> TP040 { get; set; }
        public Nullable<decimal> TP041 { get; set; }
        public string TP042 { get; set; }
        public string TP043 { get; set; }
        public string TP044 { get; set; }
        public Nullable<decimal> TP045 { get; set; }
        public Nullable<decimal> TP046 { get; set; }
        public Nullable<decimal> TP047 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
