//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMMF
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MF001 { get; set; }
        public string MF002 { get; set; }
        public string MF003 { get; set; }
        public string MF004 { get; set; }
        public string MF005 { get; set; }
        public string MF006 { get; set; }
        public string MF007 { get; set; }
        public string MF008 { get; set; }
        public Nullable<decimal> MF009 { get; set; }
        public Nullable<decimal> MF010 { get; set; }
        public Nullable<decimal> MF011 { get; set; }
        public Nullable<decimal> MF012 { get; set; }
        public Nullable<decimal> MF013 { get; set; }
        public Nullable<decimal> MF014 { get; set; }
        public string MF015 { get; set; }
        public Nullable<decimal> MF016 { get; set; }
        public string MF017 { get; set; }
        public Nullable<decimal> MF018 { get; set; }
        public Nullable<decimal> MF019 { get; set; }
        public Nullable<decimal> MF020 { get; set; }
        public string MF021 { get; set; }
        public string MF022 { get; set; }
        public string MF023 { get; set; }
        public Nullable<decimal> MF024 { get; set; }
        public Nullable<decimal> MF025 { get; set; }
        public Nullable<decimal> MF026 { get; set; }
        public string MF027 { get; set; }
        public string MF028 { get; set; }
        public string MF029 { get; set; }
        public string MF030 { get; set; }
        public string MF031 { get; set; }
        public string MF032 { get; set; }
        public Nullable<decimal> MF033 { get; set; }
        public Nullable<decimal> MF034 { get; set; }
        public Nullable<decimal> MF035 { get; set; }
        public Nullable<decimal> MF036 { get; set; }
        public Nullable<decimal> MF037 { get; set; }
        public string MF038 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
