//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMTB
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TB001 { get; set; }
        public string TB002 { get; set; }
        public string TB003 { get; set; }
        public string TB004 { get; set; }
        public string TB005 { get; set; }
        public string TB006 { get; set; }
        public string TB007 { get; set; }
        public Nullable<decimal> TB008 { get; set; }
        public string TB009 { get; set; }
        public string TB010 { get; set; }
        public string TB011 { get; set; }
        public string TB012 { get; set; }
        public string TB104 { get; set; }
        public string TB105 { get; set; }
        public string TB106 { get; set; }
        public string TB107 { get; set; }
        public Nullable<decimal> TB108 { get; set; }
        public string TB109 { get; set; }
        public string TB110 { get; set; }
        public string TB111 { get; set; }
        public string TB112 { get; set; }
        public string TB013 { get; set; }
        public string TB014 { get; set; }
        public string TB015 { get; set; }
        public Nullable<decimal> TB016 { get; set; }
        public Nullable<decimal> TB017 { get; set; }
        public Nullable<decimal> TB018 { get; set; }
        public string TB113 { get; set; }
        public string TB114 { get; set; }
        public string TB115 { get; set; }
        public Nullable<decimal> TB116 { get; set; }
        public Nullable<decimal> TB117 { get; set; }
        public Nullable<decimal> TB118 { get; set; }
        public string TB019 { get; set; }
        public string TB020 { get; set; }
        public string TB119 { get; set; }
        public string TB120 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
