//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMTJ
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TJ001 { get; set; }
        public string TJ002 { get; set; }
        public string TJ003 { get; set; }
        public string TJ004 { get; set; }
        public string TJ007 { get; set; }
        public Nullable<decimal> TJ008 { get; set; }
        public string TJ009 { get; set; }
        public string TJ010 { get; set; }
        public string TJ011 { get; set; }
        public string TJ012 { get; set; }
        public string TJ104 { get; set; }
        public string TJ107 { get; set; }
        public Nullable<decimal> TJ108 { get; set; }
        public string TJ109 { get; set; }
        public string TJ110 { get; set; }
        public string TJ111 { get; set; }
        public string TJ112 { get; set; }
        public string TJ013 { get; set; }
        public string TJ014 { get; set; }
        public string TJ015 { get; set; }
        public Nullable<decimal> TJ016 { get; set; }
        public Nullable<decimal> TJ017 { get; set; }
        public Nullable<decimal> TJ018 { get; set; }
        public string TJ113 { get; set; }
        public string TJ114 { get; set; }
        public string TJ115 { get; set; }
        public Nullable<decimal> TJ116 { get; set; }
        public Nullable<decimal> TJ117 { get; set; }
        public Nullable<decimal> TJ118 { get; set; }
        public string TJ019 { get; set; }
        public string TJ020 { get; set; }
        public string TJ119 { get; set; }
        public string TJ120 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
