//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMTK
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TK001 { get; set; }
        public string TK002 { get; set; }
        public string TK003 { get; set; }
        public string TK004 { get; set; }
        public string TK005 { get; set; }
        public Nullable<decimal> TK008 { get; set; }
        public Nullable<decimal> TK009 { get; set; }
        public Nullable<decimal> TK010 { get; set; }
        public string TK011 { get; set; }
        public string TK012 { get; set; }
        public string TK013 { get; set; }
        public string TK014 { get; set; }
        public string TK015 { get; set; }
        public string TK016 { get; set; }
        public string TK017 { get; set; }
        public string TK018 { get; set; }
        public string TK019 { get; set; }
        public Nullable<decimal> TK020 { get; set; }
        public string TK021 { get; set; }
        public string TK022 { get; set; }
        public string TK023 { get; set; }
        public string TK024 { get; set; }
        public string TK025 { get; set; }
        public string TK026 { get; set; }
        public string TK104 { get; set; }
        public string TK105 { get; set; }
        public Nullable<decimal> TK108 { get; set; }
        public Nullable<decimal> TK109 { get; set; }
        public Nullable<decimal> TK110 { get; set; }
        public string TK111 { get; set; }
        public string TK112 { get; set; }
        public string TK113 { get; set; }
        public string TK114 { get; set; }
        public string TK115 { get; set; }
        public string TK116 { get; set; }
        public string TK117 { get; set; }
        public string TK119 { get; set; }
        public Nullable<decimal> TK120 { get; set; }
        public string TK121 { get; set; }
        public string TK122 { get; set; }
        public string TK123 { get; set; }
        public string TK124 { get; set; }
        public string TK125 { get; set; }
        public string TK126 { get; set; }
        public string TK027 { get; set; }
        public string TK028 { get; set; }
        public string TK029 { get; set; }
        public Nullable<decimal> TK030 { get; set; }
        public Nullable<decimal> TK031 { get; set; }
        public Nullable<decimal> TK032 { get; set; }
        public string TK127 { get; set; }
        public string TK128 { get; set; }
        public string TK129 { get; set; }
        public Nullable<decimal> TK130 { get; set; }
        public Nullable<decimal> TK131 { get; set; }
        public Nullable<decimal> TK132 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
