//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMTC
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TC001 { get; set; }
        public string TC002 { get; set; }
        public string TC003 { get; set; }
        public string TC004 { get; set; }
        public string TC005 { get; set; }
        public string TC006 { get; set; }
        public string TC007 { get; set; }
        public Nullable<decimal> TC008 { get; set; }
        public Nullable<decimal> TC009 { get; set; }
        public Nullable<decimal> TC010 { get; set; }
        public string TC011 { get; set; }
        public string TC012 { get; set; }
        public string TC013 { get; set; }
        public string TC014 { get; set; }
        public string TC015 { get; set; }
        public string TC016 { get; set; }
        public string TC017 { get; set; }
        public string TC018 { get; set; }
        public string TC019 { get; set; }
        public Nullable<decimal> TC020 { get; set; }
        public string TC021 { get; set; }
        public string TC022 { get; set; }
        public string TC023 { get; set; }
        public string TC024 { get; set; }
        public string TC025 { get; set; }
        public string TC104 { get; set; }
        public string TC105 { get; set; }
        public string TC106 { get; set; }
        public string TC107 { get; set; }
        public Nullable<decimal> TC108 { get; set; }
        public Nullable<decimal> TC109 { get; set; }
        public Nullable<decimal> TC110 { get; set; }
        public string TC111 { get; set; }
        public string TC112 { get; set; }
        public string TC113 { get; set; }
        public string TC114 { get; set; }
        public string TC115 { get; set; }
        public string TC116 { get; set; }
        public string TC117 { get; set; }
        public string TC119 { get; set; }
        public Nullable<decimal> TC120 { get; set; }
        public string TC121 { get; set; }
        public string TC122 { get; set; }
        public string TC123 { get; set; }
        public string TC124 { get; set; }
        public string TC125 { get; set; }
        public string TC026 { get; set; }
        public string TC027 { get; set; }
        public string TC028 { get; set; }
        public Nullable<decimal> TC029 { get; set; }
        public Nullable<decimal> TC030 { get; set; }
        public Nullable<decimal> TC031 { get; set; }
        public string TC126 { get; set; }
        public string TC127 { get; set; }
        public string TC128 { get; set; }
        public Nullable<decimal> TC129 { get; set; }
        public Nullable<decimal> TC130 { get; set; }
        public Nullable<decimal> TC131 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
