//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSMV
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MV001 { get; set; }
        public string MV002 { get; set; }
        public string MV003 { get; set; }
        public string MV004 { get; set; }
        public string MV005 { get; set; }
        public string MV006 { get; set; }
        public string MV007 { get; set; }
        public string MV008 { get; set; }
        public string MV009 { get; set; }
        public string MV010 { get; set; }
        public string MV011 { get; set; }
        public string MV012 { get; set; }
        public string MV013 { get; set; }
        public string MV014 { get; set; }
        public string MV015 { get; set; }
        public string MV016 { get; set; }
        public string MV017 { get; set; }
        public string MV018 { get; set; }
        public string MV019 { get; set; }
        public string MV020 { get; set; }
        public string MV021 { get; set; }
        public string MV022 { get; set; }
        public string MV023 { get; set; }
        public string MV024 { get; set; }
        public string MV025 { get; set; }
        public string MV026 { get; set; }
        public string MV027 { get; set; }
        public string MV028 { get; set; }
        public string MV029 { get; set; }
        public string MV030 { get; set; }
        public Nullable<decimal> MV031 { get; set; }
        public string MV032 { get; set; }
        public Nullable<decimal> MV033 { get; set; }
        public string MV034 { get; set; }
        public string MV035 { get; set; }
        public string MV036 { get; set; }
        public Nullable<decimal> MV037 { get; set; }
        public string MV038 { get; set; }
        public Nullable<decimal> MV039 { get; set; }
        public Nullable<decimal> MV040 { get; set; }
        public string MV041 { get; set; }
        public string MV042 { get; set; }
        public Nullable<decimal> MV043 { get; set; }
        public string MV044 { get; set; }
        public Nullable<decimal> MV045 { get; set; }
        public string MV046 { get; set; }
        public string MV047 { get; set; }
        public string MV048 { get; set; }
        public string MV049 { get; set; }
        public string MV050 { get; set; }
        public string MV051 { get; set; }
        public string MV052 { get; set; }
        public string MV053 { get; set; }
        public string MV054 { get; set; }
        public Nullable<decimal> MV055 { get; set; }
        public Nullable<decimal> MV056 { get; set; }
        public string MV057 { get; set; }
        public string MV058 { get; set; }
        public string MV059 { get; set; }
        public string MV060 { get; set; }
        public string MV061 { get; set; }
        public string MV062 { get; set; }
        public string MV063 { get; set; }
        public string MV064 { get; set; }
        public string MV065 { get; set; }
        public string MV066 { get; set; }
        public string MV067 { get; set; }
        public string MV068 { get; set; }
        public string MV069 { get; set; }
        public string MV070 { get; set; }
        public string MV071 { get; set; }
        public string MV072 { get; set; }
        public string MV073 { get; set; }
        public string MV074 { get; set; }
        public string MV075 { get; set; }
        public string MV076 { get; set; }
        public string MV077 { get; set; }
        public string MV078 { get; set; }
        public string MV079 { get; set; }
        public Nullable<decimal> MV080 { get; set; }
        public Nullable<decimal> MV081 { get; set; }
        public Nullable<decimal> MV082 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
