//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSMQ
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MQ001 { get; set; }
        public string MQ002 { get; set; }
        public string MQ003 { get; set; }
        public string MQ004 { get; set; }
        public Nullable<decimal> MQ005 { get; set; }
        public Nullable<decimal> MQ006 { get; set; }
        public Nullable<decimal> MQ007 { get; set; }
        public string MQ008 { get; set; }
        public string MQ009 { get; set; }
        public Nullable<decimal> MQ010 { get; set; }
        public string MQ011 { get; set; }
        public string MQ012 { get; set; }
        public string MQ013 { get; set; }
        public string MQ014 { get; set; }
        public string MQ015 { get; set; }
        public string MQ016 { get; set; }
        public string MQ017 { get; set; }
        public string MQ018 { get; set; }
        public string MQ019 { get; set; }
        public string MQ020 { get; set; }
        public string MQ021 { get; set; }
        public string MQ022 { get; set; }
        public string MQ023 { get; set; }
        public string MQ024 { get; set; }
        public string MQ025 { get; set; }
        public string MQ026 { get; set; }
        public string MQ027 { get; set; }
        public string MQ028 { get; set; }
        public string MQ029 { get; set; }
        public string MQ030 { get; set; }
        public string MQ031 { get; set; }
        public string MQ032 { get; set; }
        public string MQ033 { get; set; }
        public string MQ034 { get; set; }
        public string MQ035 { get; set; }
        public string MQ036 { get; set; }
        public Nullable<decimal> MQ037 { get; set; }
        public string MQ038 { get; set; }
        public string MQ039 { get; set; }
        public string MQ040 { get; set; }
        public string MQ041 { get; set; }
        public string MQ042 { get; set; }
        public string MQ043 { get; set; }
        public string MQ044 { get; set; }
        public string MQ045 { get; set; }
        public string MQ046 { get; set; }
        public string MQ047 { get; set; }
        public string MQ048 { get; set; }
        public string MQ049 { get; set; }
        public string MQ050 { get; set; }
        public string MQ051 { get; set; }
        public Nullable<decimal> MQ052 { get; set; }
        public Nullable<decimal> MQ053 { get; set; }
        public string MQ054 { get; set; }
        public string MQ055 { get; set; }
        public string MQ056 { get; set; }
        public Nullable<decimal> MQ057 { get; set; }
        public Nullable<decimal> MQ058 { get; set; }
        public Nullable<decimal> MQ059 { get; set; }
        public string MQ060 { get; set; }
        public string MQ061 { get; set; }
        public string MQ062 { get; set; }
        public string MQ063 { get; set; }
        public string MQ064 { get; set; }
        public string MQ065 { get; set; }
        public string MQ066 { get; set; }
        public string MQ067 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
