//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSNA
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string NA001 { get; set; }
        public string NA002 { get; set; }
        public string NA003 { get; set; }
        public string NA004 { get; set; }
        public Nullable<decimal> NA005 { get; set; }
        public string NA006 { get; set; }
        public string NA007 { get; set; }
        public string NA008 { get; set; }
        public Nullable<decimal> NA009 { get; set; }
        public string NA010 { get; set; }
        public string NA011 { get; set; }
        public string NA012 { get; set; }
        public string NA013 { get; set; }
        public Nullable<decimal> NA014 { get; set; }
        public Nullable<decimal> NA015 { get; set; }
        public Nullable<decimal> NA016 { get; set; }
        public string NA017 { get; set; }
        public string NA018 { get; set; }
        public string NA019 { get; set; }
        public string NA020 { get; set; }
        public string NA021 { get; set; }
        public string NA022 { get; set; }
        public Nullable<decimal> NA023 { get; set; }
        public Nullable<decimal> NA024 { get; set; }
        public Nullable<decimal> NA025 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
