//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPAA
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string AA001 { get; set; }
        public string AA002 { get; set; }
        public string AA003 { get; set; }
        public string AA004 { get; set; }
        public string AA005 { get; set; }
        public string AA006 { get; set; }
        public string AA007 { get; set; }
        public string AA008 { get; set; }
        public string AA009 { get; set; }
        public string AA010 { get; set; }
        public string AA011 { get; set; }
        public string AA012 { get; set; }
        public string AA013 { get; set; }
        public string AA014 { get; set; }
        public string AA015 { get; set; }
        public string AA016 { get; set; }
        public string AA017 { get; set; }
        public string AA018 { get; set; }
        public string AA019 { get; set; }
        public string AA020 { get; set; }
        public string AA021 { get; set; }
        public string AA022 { get; set; }
        public Nullable<decimal> AA023 { get; set; }
        public Nullable<decimal> AA024 { get; set; }
        public string AA025 { get; set; }
        public string AA026 { get; set; }
        public string AA027 { get; set; }
        public string AA028 { get; set; }
        public string AA029 { get; set; }
        public string AA030 { get; set; }
        public string AA031 { get; set; }
        public string AA032 { get; set; }
        public string AA033 { get; set; }
        public string AA034 { get; set; }
        public string AA035 { get; set; }
        public string AA036 { get; set; }
        public Nullable<decimal> AA037 { get; set; }
        public Nullable<decimal> AA038 { get; set; }
        public Nullable<decimal> AA039 { get; set; }
        public Nullable<decimal> AA040 { get; set; }
        public Nullable<decimal> AA041 { get; set; }
        public Nullable<decimal> AA042 { get; set; }
        public Nullable<decimal> AA043 { get; set; }
        public Nullable<decimal> AA044 { get; set; }
        public Nullable<decimal> AA045 { get; set; }
        public Nullable<decimal> AA046 { get; set; }
        public Nullable<decimal> AA047 { get; set; }
        public Nullable<decimal> AA048 { get; set; }
        public Nullable<decimal> AA049 { get; set; }
        public string AA050 { get; set; }
        public string AA051 { get; set; }
        public string AA052 { get; set; }
        public string AA053 { get; set; }
        public Nullable<decimal> AA054 { get; set; }
        public Nullable<decimal> AA055 { get; set; }
        public Nullable<decimal> AA056 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
