//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPAB
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string AB001 { get; set; }
        public string AB002 { get; set; }
        public string AB003 { get; set; }
        public string AB004 { get; set; }
        public string AB005 { get; set; }
        public string AB006 { get; set; }
        public string AB007 { get; set; }
        public string AB008 { get; set; }
        public string AB009 { get; set; }
        public Nullable<decimal> AB010 { get; set; }
        public Nullable<decimal> AB011 { get; set; }
        public Nullable<decimal> AB012 { get; set; }
        public Nullable<decimal> AB013 { get; set; }
        public Nullable<decimal> AB014 { get; set; }
        public Nullable<decimal> AB015 { get; set; }
        public Nullable<decimal> AB016 { get; set; }
        public Nullable<decimal> AB017 { get; set; }
        public Nullable<decimal> AB018 { get; set; }
        public Nullable<decimal> AB019 { get; set; }
        public Nullable<decimal> AB020 { get; set; }
        public Nullable<decimal> AB021 { get; set; }
        public Nullable<decimal> AB022 { get; set; }
        public string AB023 { get; set; }
        public string AB024 { get; set; }
        public string AB025 { get; set; }
        public string AB026 { get; set; }
        public string AB027 { get; set; }
        public string AB028 { get; set; }
        public Nullable<decimal> AB029 { get; set; }
        public Nullable<decimal> AB030 { get; set; }
        public Nullable<decimal> AB031 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
