//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPAD
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string AD001 { get; set; }
        public string AD002 { get; set; }
        public string AD003 { get; set; }
        public string AD004 { get; set; }
        public string AD005 { get; set; }
        public string AD006 { get; set; }
        public string AD007 { get; set; }
        public string AD008 { get; set; }
        public string AD009 { get; set; }
        public string AD010 { get; set; }
        public Nullable<decimal> AD011 { get; set; }
        public Nullable<decimal> AD012 { get; set; }
        public Nullable<decimal> AD013 { get; set; }
        public Nullable<decimal> AD014 { get; set; }
        public Nullable<decimal> AD015 { get; set; }
        public Nullable<decimal> AD016 { get; set; }
        public Nullable<decimal> AD017 { get; set; }
        public Nullable<decimal> AD018 { get; set; }
        public string AD019 { get; set; }
        public string AD020 { get; set; }
        public string AD021 { get; set; }
        public string AD022 { get; set; }
        public string AD023 { get; set; }
        public string AD024 { get; set; }
        public string AD025 { get; set; }
        public string AD026 { get; set; }
        public string AD027 { get; set; }
        public Nullable<decimal> AD028 { get; set; }
        public Nullable<decimal> AD029 { get; set; }
        public Nullable<decimal> AD030 { get; set; }
        public Nullable<decimal> AD031 { get; set; }
        public Nullable<decimal> AD032 { get; set; }
        public Nullable<decimal> AD033 { get; set; }
        public Nullable<decimal> AD034 { get; set; }
        public Nullable<decimal> AD035 { get; set; }
        public Nullable<decimal> AD036 { get; set; }
        public Nullable<decimal> AD037 { get; set; }
        public Nullable<decimal> AD038 { get; set; }
        public Nullable<decimal> AD039 { get; set; }
        public Nullable<decimal> AD040 { get; set; }
        public string AD041 { get; set; }
        public string AD042 { get; set; }
        public string AD043 { get; set; }
        public string AD044 { get; set; }
        public string AD045 { get; set; }
        public string AD046 { get; set; }
        public string AD047 { get; set; }
        public Nullable<decimal> AD048 { get; set; }
        public Nullable<decimal> AD049 { get; set; }
        public Nullable<decimal> AD050 { get; set; }
        public string AD051 { get; set; }
        public string AD052 { get; set; }
        public string AD053 { get; set; }
        public Nullable<decimal> AD054 { get; set; }
        public Nullable<decimal> AD055 { get; set; }
        public Nullable<decimal> AD056 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
