//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPAC
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string AC001 { get; set; }
        public string AC002 { get; set; }
        public string AC003 { get; set; }
        public string AC004 { get; set; }
        public string AC005 { get; set; }
        public string AC006 { get; set; }
        public string AC007 { get; set; }
        public string AC008 { get; set; }
        public string AC009 { get; set; }
        public string AC010 { get; set; }
        public string AC011 { get; set; }
        public string AC012 { get; set; }
        public string AC013 { get; set; }
        public string AC014 { get; set; }
        public string AC015 { get; set; }
        public string AC016 { get; set; }
        public string AC017 { get; set; }
        public string AC018 { get; set; }
        public string AC019 { get; set; }
        public string AC020 { get; set; }
        public string AC021 { get; set; }
        public string AC022 { get; set; }
        public string AC023 { get; set; }
        public string AC024 { get; set; }
        public string AC025 { get; set; }
        public string AC026 { get; set; }
        public string AC027 { get; set; }
        public string AC028 { get; set; }
        public string AC029 { get; set; }
        public string AC030 { get; set; }
        public string AC031 { get; set; }
        public string AC032 { get; set; }
        public string AC033 { get; set; }
        public string AC034 { get; set; }
        public string AC035 { get; set; }
        public string AC036 { get; set; }
        public string AC037 { get; set; }
        public string AC038 { get; set; }
        public string AC039 { get; set; }
        public string AC040 { get; set; }
        public string AC041 { get; set; }
        public string AC042 { get; set; }
        public string AC043 { get; set; }
        public string AC044 { get; set; }
        public string AC045 { get; set; }
        public string AC046 { get; set; }
        public string AC047 { get; set; }
        public string AC048 { get; set; }
        public string AC049 { get; set; }
        public string AC050 { get; set; }
        public string AC051 { get; set; }
        public string AC052 { get; set; }
        public string AC053 { get; set; }
        public string AC054 { get; set; }
        public string AC055 { get; set; }
        public string AC056 { get; set; }
        public string AC057 { get; set; }
        public string AC058 { get; set; }
        public string AC059 { get; set; }
        public string AC060 { get; set; }
        public string AC061 { get; set; }
        public Nullable<decimal> AC062 { get; set; }
        public Nullable<decimal> AC063 { get; set; }
        public string AC064 { get; set; }
        public string AC065 { get; set; }
        public string AC066 { get; set; }
        public string AC067 { get; set; }
        public Nullable<decimal> AC068 { get; set; }
        public Nullable<decimal> AC069 { get; set; }
        public Nullable<decimal> AC070 { get; set; }
        public string AC071 { get; set; }
        public string AC072 { get; set; }
        public string AC073 { get; set; }
        public Nullable<decimal> AC074 { get; set; }
        public Nullable<decimal> AC075 { get; set; }
        public Nullable<decimal> AC076 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
