//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPMA
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MA001 { get; set; }
        public string MA002 { get; set; }
        public string MA003 { get; set; }
        public string MA004 { get; set; }
        public string MA005 { get; set; }
        public string MA006 { get; set; }
        public string MA007 { get; set; }
        public string MA008 { get; set; }
        public string MA009 { get; set; }
        public string MA010 { get; set; }
        public Nullable<decimal> MA011 { get; set; }
        public Nullable<decimal> MA012 { get; set; }
        public Nullable<decimal> MA013 { get; set; }
        public string MA014 { get; set; }
        public string MA015 { get; set; }
        public string MA016 { get; set; }
        public string MA017 { get; set; }
        public string MA018 { get; set; }
        public string MA019 { get; set; }
        public string MA020 { get; set; }
        public string MA021 { get; set; }
        public string MA022 { get; set; }
        public string MA023 { get; set; }
        public string MA024 { get; set; }
        public string MA025 { get; set; }
        public string MA026 { get; set; }
        public string MA027 { get; set; }
        public string MA028 { get; set; }
        public string MA029 { get; set; }
        public string MA030 { get; set; }
        public string MA031 { get; set; }
        public string MA032 { get; set; }
        public Nullable<decimal> MA033 { get; set; }
        public Nullable<decimal> MA034 { get; set; }
        public string MA035 { get; set; }
        public Nullable<decimal> MA036 { get; set; }
        public string MA037 { get; set; }
        public string MA038 { get; set; }
        public string MA039 { get; set; }
        public string MA040 { get; set; }
        public string MA041 { get; set; }
        public string MA042 { get; set; }
        public string MA043 { get; set; }
        public Nullable<decimal> MA044 { get; set; }
        public Nullable<decimal> MA045 { get; set; }
        public string MA046 { get; set; }
        public string MA047 { get; set; }
        public string MA048 { get; set; }
        public string MA049 { get; set; }
        public string MA050 { get; set; }
        public string MA051 { get; set; }
        public string MA052 { get; set; }
        public string MA053 { get; set; }
        public string MA054 { get; set; }
        public string MA055 { get; set; }
        public string MA056 { get; set; }
        public string MA057 { get; set; }
        public string MA058 { get; set; }
        public Nullable<decimal> MA059 { get; set; }
        public Nullable<decimal> MA060 { get; set; }
        public Nullable<decimal> MA061 { get; set; }
        public string MA062 { get; set; }
        public string MA063 { get; set; }
        public string MA064 { get; set; }
        public string MA065 { get; set; }
        public string MA066 { get; set; }
        public Nullable<decimal> MA067 { get; set; }
        public string MA068 { get; set; }
        public string MA069 { get; set; }
        public string MA070 { get; set; }
        public string MA071 { get; set; }
        public string MA072 { get; set; }
        public string MA073 { get; set; }
        public string MA074 { get; set; }
        public string MA075 { get; set; }
        public string MA076 { get; set; }
        public string MA077 { get; set; }
        public string MA078 { get; set; }
        public string MA079 { get; set; }
        public string MA080 { get; set; }
        public string MA081 { get; set; }
        public string MA082 { get; set; }
        public string MA083 { get; set; }
        public string MA084 { get; set; }
        public string MA085 { get; set; }
        public string MA086 { get; set; }
        public string MA087 { get; set; }
        public string MA088 { get; set; }
        public string MA089 { get; set; }
        public Nullable<decimal> MA090 { get; set; }
        public Nullable<decimal> MA091 { get; set; }
        public Nullable<decimal> MA092 { get; set; }
        public Nullable<decimal> MA093 { get; set; }
        public Nullable<decimal> MA094 { get; set; }
        public Nullable<decimal> MA095 { get; set; }
        public string MA096 { get; set; }
        public string MA097 { get; set; }
        public string MA098 { get; set; }
        public string MA099 { get; set; }
        public string MA100 { get; set; }
        public Nullable<decimal> MA101 { get; set; }
        public string MA102 { get; set; }
        public string MA103 { get; set; }
        public Nullable<decimal> MA104 { get; set; }
        public string MA105 { get; set; }
        public string MA106 { get; set; }
        public string MA107 { get; set; }
        public string MA108 { get; set; }
        public Nullable<decimal> MA109 { get; set; }
        public Nullable<decimal> MA110 { get; set; }
        public Nullable<decimal> MA111 { get; set; }
        public string MA112 { get; set; }
        public string MA113 { get; set; }
        public string MA114 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
