//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPTI
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TI001 { get; set; }
        public string TI002 { get; set; }
        public string TI003 { get; set; }
        public string TI004 { get; set; }
        public string TI005 { get; set; }
        public string TI006 { get; set; }
        public string TI007 { get; set; }
        public string TI008 { get; set; }
        public Nullable<decimal> TI009 { get; set; }
        public Nullable<decimal> TI010 { get; set; }
        public Nullable<decimal> TI011 { get; set; }
        public string TI012 { get; set; }
        public string TI013 { get; set; }
        public string TI014 { get; set; }
        public string TI015 { get; set; }
        public Nullable<decimal> TI016 { get; set; }
        public string TI017 { get; set; }
        public string TI018 { get; set; }
        public string TI019 { get; set; }
        public string TI020 { get; set; }
        public string TI021 { get; set; }
        public string TI022 { get; set; }
        public string TI023 { get; set; }
        public string TI024 { get; set; }
        public string TI025 { get; set; }
        public string TI026 { get; set; }
        public string TI027 { get; set; }
        public Nullable<decimal> TI028 { get; set; }
        public Nullable<decimal> TI029 { get; set; }
        public string TI030 { get; set; }
        public string TI031 { get; set; }
        public string TI032 { get; set; }
        public string TI033 { get; set; }
        public string TI034 { get; set; }
        public string TI035 { get; set; }
        public Nullable<decimal> TI036 { get; set; }
        public Nullable<decimal> TI037 { get; set; }
        public Nullable<decimal> TI038 { get; set; }
        public string TI039 { get; set; }
        public Nullable<decimal> TI040 { get; set; }
        public string TI041 { get; set; }
        public string TI042 { get; set; }
        public string TI043 { get; set; }
        public string TI044 { get; set; }
        public string TI045 { get; set; }
        public Nullable<decimal> TI046 { get; set; }
        public string TI047 { get; set; }
        public string TI048 { get; set; }
        public string TI049 { get; set; }
        public string TI050 { get; set; }
        public string TI051 { get; set; }
        public Nullable<decimal> TI052 { get; set; }
        public Nullable<decimal> TI053 { get; set; }
        public Nullable<decimal> TI054 { get; set; }
        public string TI055 { get; set; }
        public string TI056 { get; set; }
        public string TI057 { get; set; }
        public Nullable<decimal> TI058 { get; set; }
        public Nullable<decimal> TI059 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
