//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPTF
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TF001 { get; set; }
        public string TF002 { get; set; }
        public string TF003 { get; set; }
        public string TF004 { get; set; }
        public string TF005 { get; set; }
        public string TF006 { get; set; }
        public string TF007 { get; set; }
        public string TF008 { get; set; }
        public Nullable<decimal> TF009 { get; set; }
        public string TF010 { get; set; }
        public Nullable<decimal> TF011 { get; set; }
        public string TF012 { get; set; }
        public Nullable<decimal> TF013 { get; set; }
        public Nullable<decimal> TF014 { get; set; }
        public string TF015 { get; set; }
        public string TF016 { get; set; }
        public string TF017 { get; set; }
        public string TF018 { get; set; }
        public string TF019 { get; set; }
        public Nullable<decimal> TF020 { get; set; }
        public Nullable<decimal> TF021 { get; set; }
        public string TF022 { get; set; }
        public string TF023 { get; set; }
        public Nullable<decimal> TF024 { get; set; }
        public Nullable<decimal> TF025 { get; set; }
        public Nullable<decimal> TF026 { get; set; }
        public Nullable<decimal> TF027 { get; set; }
        public string TF028 { get; set; }
        public Nullable<decimal> TF029 { get; set; }
        public Nullable<decimal> TF030 { get; set; }
        public Nullable<decimal> TF031 { get; set; }
        public string TF033 { get; set; }
        public string TF046 { get; set; }
        public Nullable<decimal> TF047 { get; set; }
        public Nullable<decimal> TF048 { get; set; }
        public Nullable<decimal> TF049 { get; set; }
        public Nullable<decimal> TF050 { get; set; }
        public string TF104 { get; set; }
        public string TF105 { get; set; }
        public string TF106 { get; set; }
        public string TF107 { get; set; }
        public string TF108 { get; set; }
        public Nullable<decimal> TF109 { get; set; }
        public string TF110 { get; set; }
        public Nullable<decimal> TF111 { get; set; }
        public string TF112 { get; set; }
        public Nullable<decimal> TF113 { get; set; }
        public Nullable<decimal> TF114 { get; set; }
        public string TF115 { get; set; }
        public string TF116 { get; set; }
        public string TF117 { get; set; }
        public Nullable<decimal> TF120 { get; set; }
        public Nullable<decimal> TF121 { get; set; }
        public string TF122 { get; set; }
        public Nullable<decimal> TF123 { get; set; }
        public Nullable<decimal> TF124 { get; set; }
        public string TF125 { get; set; }
        public Nullable<decimal> TF126 { get; set; }
        public Nullable<decimal> TF127 { get; set; }
        public Nullable<decimal> TF128 { get; set; }
        public Nullable<decimal> TF129 { get; set; }
        public Nullable<decimal> TF130 { get; set; }
        public Nullable<decimal> TF131 { get; set; }
        public string TF132 { get; set; }
        public Nullable<decimal> TF133 { get; set; }
        public Nullable<decimal> TF134 { get; set; }
        public Nullable<decimal> TF135 { get; set; }
        public Nullable<decimal> TF136 { get; set; }
        public Nullable<decimal> TF137 { get; set; }
        public string TF032 { get; set; }
        public string TF138 { get; set; }
        public string TF139 { get; set; }
        public string TF034 { get; set; }
        public string TF035 { get; set; }
        public string TF036 { get; set; }
        public Nullable<decimal> TF037 { get; set; }
        public Nullable<decimal> TF038 { get; set; }
        public Nullable<decimal> TF039 { get; set; }
        public string TF140 { get; set; }
        public string TF141 { get; set; }
        public string TF142 { get; set; }
        public Nullable<decimal> TF143 { get; set; }
        public Nullable<decimal> TF144 { get; set; }
        public Nullable<decimal> TF145 { get; set; }
        public string TF146 { get; set; }
        public Nullable<decimal> TF147 { get; set; }
        public Nullable<decimal> TF148 { get; set; }
        public Nullable<decimal> TF149 { get; set; }
        public Nullable<decimal> TF150 { get; set; }
        public string TF040 { get; set; }
        public string TF151 { get; set; }
        public string TF041 { get; set; }
        public string TF152 { get; set; }
        public string TF200 { get; set; }
        public string TF201 { get; set; }
        public string TF202 { get; set; }
        public string TF203 { get; set; }
        public string TF204 { get; set; }
        public string TF210 { get; set; }
        public string TF211 { get; set; }
        public string TF212 { get; set; }
        public string TF213 { get; set; }
        public string TF214 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
