//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPTT
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TT001 { get; set; }
        public string TT002 { get; set; }
        public string TT003 { get; set; }
        public string TT004 { get; set; }
        public string TT005 { get; set; }
        public string TT006 { get; set; }
        public string TT007 { get; set; }
        public Nullable<decimal> TT008 { get; set; }
        public Nullable<decimal> TT009 { get; set; }
        public string TT010 { get; set; }
        public string TT011 { get; set; }
        public string TT012 { get; set; }
        public string TT013 { get; set; }
        public string TT014 { get; set; }
        public string TT015 { get; set; }
        public string TT016 { get; set; }
        public string TT017 { get; set; }
        public string TT018 { get; set; }
        public Nullable<decimal> TT019 { get; set; }
        public Nullable<decimal> TT020 { get; set; }
        public Nullable<decimal> TT021 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
