//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTW
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TW001 { get; set; }
        public string TW002 { get; set; }
        public string TW003 { get; set; }
        public string TW004 { get; set; }
        public string TW005 { get; set; }
        public string TW006 { get; set; }
        public string TW007 { get; set; }
        public string TW008 { get; set; }
        public string TW009 { get; set; }
        public string TW010 { get; set; }
        public string TW011 { get; set; }
        public Nullable<decimal> TW012 { get; set; }
        public string TW013 { get; set; }
        public string TW014 { get; set; }
        public Nullable<decimal> TW015 { get; set; }
        public string TW016 { get; set; }
        public string TW017 { get; set; }
        public string TW018 { get; set; }
        public Nullable<decimal> TW019 { get; set; }
        public Nullable<decimal> TW020 { get; set; }
        public Nullable<decimal> TW021 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
