//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeanSerialEntities : DbContext
    {
        public LeanSerialEntities()
            : base("name=LeanSerialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DTASSET_SCANNER_ALL> DTASSET_SCANNER_ALL { get; set; }
        public virtual DbSet<DTASSET_SCANNER_IN> DTASSET_SCANNER_IN { get; set; }
        public virtual DbSet<DTASSET_SCANNER_IN_SUB> DTASSET_SCANNER_IN_SUB { get; set; }
        public virtual DbSet<DTASSET_SCANNER_OUT> DTASSET_SCANNER_OUT { get; set; }
        public virtual DbSet<DTASSET_SCANNER_OUT_SUB> DTASSET_SCANNER_OUT_SUB { get; set; }
        public virtual DbSet<DTASSET_SCANNER_UP> DTASSET_SCANNER_UP { get; set; }
    }
}
