//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCMSML
    {
        public string ML001 { get; set; }
        public string ML002 { get; set; }
        public string ML003 { get; set; }
        public string ML004 { get; set; }
        public Nullable<decimal> ML005 { get; set; }
        public int ID { get; set; }
    }
}
