//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAILPLAN
    {
        public int ID { get; set; }
        public int NO { get; set; }
        public string WORKINGHOURS { get; set; }
        public Nullable<double> PLANQTY { get; set; }
        public Nullable<int> ACTUALQTY { get; set; }
        public string REASON { get; set; }
        public string REASONflg { get; set; }
        public string REASONTEXT { get; set; }
    }
}
