//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DHQMD
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MD001 { get; set; }
        public string MD002 { get; set; }
        public string MD003 { get; set; }
        public string MD004 { get; set; }
        public string MD005 { get; set; }
        public string MD006 { get; set; }
        public string MD007 { get; set; }
        public Nullable<decimal> MD008 { get; set; }
        public Nullable<decimal> MD009 { get; set; }
        public string MD010 { get; set; }
        public string MD011 { get; set; }
        public string MD012 { get; set; }
        public string MD013 { get; set; }
        public string MD014 { get; set; }
        public string MD015 { get; set; }
        public string MD016 { get; set; }
        public string MD017 { get; set; }
        public string MD018 { get; set; }
        public string MD019 { get; set; }
        public string MD020 { get; set; }
        public string MD021 { get; set; }
        public string MD022 { get; set; }
        public string MD023 { get; set; }
        public string MD024 { get; set; }
        public string MD025 { get; set; }
        public string MD026 { get; set; }
        public string MD027 { get; set; }
        public string MD028 { get; set; }
        public string MD029 { get; set; }
        public string MD030 { get; set; }
        public string MD031 { get; set; }
        public string MD032 { get; set; }
        public string MD033 { get; set; }
        public string MD034 { get; set; }
        public string MD035 { get; set; }
        public string MD036 { get; set; }
        public string MD037 { get; set; }
        public string MD038 { get; set; }
        public Nullable<decimal> MD039 { get; set; }
        public Nullable<decimal> MD040 { get; set; }
        public Nullable<decimal> MD041 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
