//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTABOM_modelindex
    {
        public string MODELHBN { get; set; }
        public string MODELNAME { get; set; }
        public string MODELLOT { get; set; }
        public string MODELTYPE { get; set; }
        public string EXPORTER { get; set; }
        public string V { get; set; }
        public string LABMADE { get; set; }
        public string SAFESPEC { get; set; }
        public string NOTE { get; set; }
        public string CTRLNO { get; set; }
        public string ST { get; set; }
    }
}
