//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTABOM_ModeltoParts
    {
        public string 机种 { get; set; }
        public string 品号1 { get; set; }
        public string 品号2 { get; set; }
        public string 品号3 { get; set; }
        public string 品号4 { get; set; }
        public string 品号5 { get; set; }
        public string 品号6 { get; set; }
        public string 品号7 { get; set; }
        public string 品号8 { get; set; }
        public string 品号9 { get; set; }
        public string 品号10 { get; set; }
        public string 品号11 { get; set; }
        public string 品号12 { get; set; }
        public string 品号13 { get; set; }
        public string 品号14 { get; set; }
        public string 品号15 { get; set; }
        public string 品号16 { get; set; }
        public string 品号17 { get; set; }
        public string 品号18 { get; set; }
    }
}
