//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTAREALTIMESHEET
    {
        public Nullable<System.DateTime> REALCREATEDATE { get; set; }
        public string REALCREATENAME { get; set; }
        public string REALMODEL { get; set; }
        public string REALFPHBN { get; set; }
        public string REALFPTEXT { get; set; }
        public string REALSFPHBN { get; set; }
        public string REALSFPTEXT { get; set; }
        public Nullable<decimal> REALSMTSHORT { get; set; }
        public Nullable<decimal> REALSMT { get; set; }
        public Nullable<decimal> REALAISHORT { get; set; }
        public Nullable<decimal> REALAI { get; set; }
        public Nullable<decimal> REALHI { get; set; }
        public Nullable<decimal> REALMODI { get; set; }
        public Nullable<decimal> REALPCBSUB { get; set; }
        public Nullable<decimal> REALP2DTOTAL { get; set; }
        public Nullable<decimal> REALPCBASUB { get; set; }
        public Nullable<decimal> REALSUB { get; set; }
        public Nullable<decimal> REALASSEMBLY { get; set; }
        public Nullable<decimal> REALCHECK { get; set; }
        public Nullable<decimal> REALOUTER { get; set; }
        public Nullable<decimal> REALINSPECT { get; set; }
        public Nullable<decimal> REALPACKING { get; set; }
        public Nullable<decimal> REALP1DTOTAL { get; set; }
        public Nullable<decimal> REALTOTAL { get; set; }
        public Nullable<decimal> REALREAL { get; set; }
        public Nullable<decimal> REALYIFEI { get; set; }
        public string REALMODINAME { get; set; }
        public Nullable<System.DateTime> REALMODIDATE { get; set; }
        public string REALUID { get; set; }
        public string REALCNAME { get; set; }
        public string REALPNAME { get; set; }
        public string REALIPADDR { get; set; }
        public string REALCOUNT { get; set; }
        public Nullable<decimal> REALUDF01 { get; set; }
        public Nullable<decimal> REALUDF02 { get; set; }
        public Nullable<decimal> REALUDF03 { get; set; }
        public Nullable<decimal> REALUDF04 { get; set; }
        public Nullable<decimal> REALUDF05 { get; set; }
        public string REALUDF51 { get; set; }
        public string REALUDF52 { get; set; }
        public string REALUDF53 { get; set; }
        public string REALUDF54 { get; set; }
        public string REALUDF55 { get; set; }
    }
}
