//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_COPTA
    {
        public string tapono { get; set; }
        public string tapoinv { get; set; }
        public string taitem { get; set; }
        public string tadesc { get; set; }
        public int tanum { get; set; }
        public Nullable<int> tanumall { get; set; }
        public string tadate { get; set; }
        public string tareg { get; set; }
        public string tamemo { get; set; }
        public string taudfchar1 { get; set; }
        public string taudfchar2 { get; set; }
        public string taudfchar3 { get; set; }
        public string taudfchar4 { get; set; }
        public Nullable<int> taudfint1 { get; set; }
        public Nullable<int> taudfint2 { get; set; }
        public Nullable<int> taudfint3 { get; set; }
        public Nullable<int> taudfint4 { get; set; }
    }
}
