//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_SCANNER_UP
    {
        public int ID { get; set; }
        public string OUTS001 { get; set; }
        public string OUTS002 { get; set; }
        public string OUTS003 { get; set; }
        public string OUTS004 { get; set; }
        public string OUTS005 { get; set; }
        public string OUTS006 { get; set; }
        public string OUTS007 { get; set; }
        public Nullable<int> OUTS008 { get; set; }
        public string OUTSYSUID { get; set; }
        public string OUTHNAME { get; set; }
        public string OUTHIP { get; set; }
        public string OUTHMAC { get; set; }
        public string OUTUSER { get; set; }
        public string OUTDTIME { get; set; }
        public string studfchar1 { get; set; }
        public string studfchar2 { get; set; }
        public string studfchar3 { get; set; }
        public string studfchar4 { get; set; }
        public Nullable<int> studfint1 { get; set; }
        public Nullable<int> studfint2 { get; set; }
        public Nullable<int> studfint3 { get; set; }
        public Nullable<int> studfint4 { get; set; }
    }
}
