//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_USER
    {
        public string username { get; set; }
        public string userpwd { get; set; }
        public Nullable<System.DateTime> userdate { get; set; }
        public Nullable<int> pro1 { get; set; }
        public Nullable<int> pro2 { get; set; }
        public Nullable<int> bukan { get; set; }
        public Nullable<int> report { get; set; }
        public string dept { get; set; }
        public int sysadmin { get; set; }
        public string memo { get; set; }
    }
}
