//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_PORT
    {
        public int poid { get; set; }
        public string poportchs { get; set; }
        public string poporteng { get; set; }
        public string pocounty { get; set; }
        public string poportcode { get; set; }
        public string pocountchs { get; set; }
        public string pocounteng { get; set; }
        public string memo { get; set; }
    }
}
