//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_TIMING
    {
        public int tiid { get; set; }
        public string timemo { get; set; }
        public string tidate { get; set; }
        public string tisysuid { get; set; }
        public string tiuserid { get; set; }
        public string tihostname { get; set; }
        public string tihostip { get; set; }
        public string tihostmac { get; set; }
    }
}
