//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_STOCK
    {
        public string ststockno { get; set; }
        public string stlotno { get; set; }
        public string stitem { get; set; }
        public string stparts { get; set; }
        public string stprono { get; set; }
        public Nullable<int> stpromun { get; set; }
        public string stmocta { get; set; }
        public Nullable<int> stmocmun { get; set; }
        public string stcopno { get; set; }
        public string stmoclot { get; set; }
        public string stmocpno { get; set; }
        public string stmocdate { get; set; }
        public string stpdate { get; set; }
        public string steps { get; set; }
        public string stepsdate { get; set; }
        public string stuserid { get; set; }
        public string sthostname { get; set; }
        public string sthostip { get; set; }
        public string sthostmac { get; set; }
        public string stmemo { get; set; }
        public string studfchar1 { get; set; }
        public string studfchar2 { get; set; }
        public string studfchar3 { get; set; }
        public string studfchar4 { get; set; }
        public Nullable<int> studfint1 { get; set; }
        public Nullable<int> studfint2 { get; set; }
        public Nullable<int> studfint3 { get; set; }
        public Nullable<int> studfint4 { get; set; }
    }
}
