//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_COPTB
    {
        public string tbpono { get; set; }
        public string tbpoinv { get; set; }
        public string tbitem { get; set; }
        public string tbdesc { get; set; }
        public Nullable<int> tbnum { get; set; }
        public string tbdate { get; set; }
        public string tbreg { get; set; }
        public string tbmemo { get; set; }
        public string tbudfchar1 { get; set; }
        public string tbudfchar2 { get; set; }
        public string tbudfchar3 { get; set; }
        public string tbudfchar4 { get; set; }
        public Nullable<int> tbudfint1 { get; set; }
        public Nullable<int> tbudfint2 { get; set; }
        public Nullable<int> tbudfint3 { get; set; }
        public Nullable<int> tbudfint4 { get; set; }
    }
}
