//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_SHIPINV
    {
        public string buno { get; set; }
        public string buitem { get; set; }
        public string bumodel { get; set; }
        public string prosn { get; set; }
        public Nullable<int> pronum { get; set; }
        public string budate { get; set; }
    }
}
