//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_PREVIEW
    {
        public int weid { get; set; }
        public string wedates { get; set; }
        public string wedatet { get; set; }
        public Nullable<int> weltdnum { get; set; }
        public string weltdalg { get; set; }
        public string weltda { get; set; }
        public Nullable<int> weltdanum { get; set; }
        public string weltdana { get; set; }
        public string weltdanb { get; set; }
        public string weltdanc { get; set; }
        public string weltdand { get; set; }
        public string weltdane { get; set; }
        public string weltdanf { get; set; }
        public string weltdblg { get; set; }
        public string weltdb { get; set; }
        public Nullable<int> weltdbnum { get; set; }
        public string weltdbna { get; set; }
        public string weltdbnb { get; set; }
        public string weltdbnc { get; set; }
        public string weltdbnd { get; set; }
        public string weltdbne { get; set; }
        public string weltdbnf { get; set; }
        public string weltdclg { get; set; }
        public string weltdc { get; set; }
        public Nullable<int> weltdcnum { get; set; }
        public string weltdcna { get; set; }
        public string weltdcnb { get; set; }
        public string weltdcnc { get; set; }
        public string weltdcnd { get; set; }
        public string weltdcne { get; set; }
        public string weltdcnf { get; set; }
        public string weltdcng { get; set; }
        public string weltdd { get; set; }
        public Nullable<int> weltddnum { get; set; }
        public string weltddna { get; set; }
        public string weltddnb { get; set; }
        public string weltddnc { get; set; }
        public string weltddnd { get; set; }
        public string weltddne { get; set; }
        public string weltddnf { get; set; }
        public string weltddng { get; set; }
        public string wesysuid { get; set; }
        public string weuserid { get; set; }
        public string wehostname { get; set; }
        public string wehostip { get; set; }
        public string wehostmac { get; set; }
        public string wememo { get; set; }
        public string weudfchar1 { get; set; }
        public string weudfchar2 { get; set; }
        public string weudfchar3 { get; set; }
        public string weudfchar4 { get; set; }
        public Nullable<int> weudfint1 { get; set; }
        public Nullable<int> weudfint2 { get; set; }
        public Nullable<int> weudfint3 { get; set; }
        public Nullable<int> weudfint4 { get; set; }
    }
}
