//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_PRO1PA
    {
        public string palot { get; set; }
        public string palines { get; set; }
        public string paday { get; set; }
        public string pamodel { get; set; }
        public string paitem { get; set; }
        public string palotnum { get; set; }
        public string pamocta { get; set; }
        public string pamocnum { get; set; }
        public string paprosn { get; set; }
        public string papdate { get; set; }
        public string papcbnum { get; set; }
        public string parepair { get; set; }
        public string paredatea { get; set; }
        public string parecodea { get; set; }
        public string parenamea { get; set; }
        public string pangcodea { get; set; }
        public string pangnamea { get; set; }
        public string paredateb { get; set; }
        public string parecodeb { get; set; }
        public string parenameb { get; set; }
        public string pangcodeb { get; set; }
        public string pangnameb { get; set; }
        public string paredatec { get; set; }
        public string parecodec { get; set; }
        public string parenamec { get; set; }
        public string pangcodec { get; set; }
        public string pangnamec { get; set; }
        public string pauserid { get; set; }
        public string pahostname { get; set; }
        public string pahostip { get; set; }
        public string pahostmac { get; set; }
        public string paeps { get; set; }
        public string paepsdate { get; set; }
        public string pamemo { get; set; }
        public string paudfchar1 { get; set; }
        public string paudfchar2 { get; set; }
        public string paudfchar3 { get; set; }
        public string paudfchar4 { get; set; }
        public Nullable<int> paudfint1 { get; set; }
        public Nullable<int> paudfint2 { get; set; }
        public Nullable<int> paudfint3 { get; set; }
        public Nullable<int> paudfint4 { get; set; }
    }
}
