//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_USERLOG
    {
        public int myusid { get; set; }
        public string myuser { get; set; }
        public string myname { get; set; }
        public string myip { get; set; }
        public string mymac { get; set; }
        public Nullable<System.DateTime> mymem { get; set; }
        public string memo { get; set; }
        public string myudfchar1 { get; set; }
        public string myudfchar2 { get; set; }
        public string myudfchar3 { get; set; }
        public string myudfchar4 { get; set; }
        public Nullable<int> myudfint1 { get; set; }
        public Nullable<int> myudfint2 { get; set; }
        public Nullable<int> myudfint3 { get; set; }
        public Nullable<int> myudfint4 { get; set; }
    }
}
