//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_DAYS
    {
        public int daid { get; set; }
        public string dacode { get; set; }
        public string daname { get; set; }
        public string damemo { get; set; }
        public string daudfchar1 { get; set; }
        public string daudfchar2 { get; set; }
        public string daudfchar3 { get; set; }
        public string daudfchar4 { get; set; }
        public Nullable<int> daudfint1 { get; set; }
        public Nullable<int> daudfint2 { get; set; }
        public Nullable<int> daudfint3 { get; set; }
        public Nullable<int> daudfint4 { get; set; }
    }
}
