//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_SCANNER_OUT_SUB
    {
        public int ID { get; set; }
        public string OUTS001 { get; set; }
        public string OUTS002 { get; set; }
        public string OUTS003 { get; set; }
        public string OUTS004 { get; set; }
        public string OUTS005 { get; set; }
        public Nullable<int> OUTS006 { get; set; }
        public string OUTS007 { get; set; }
        public string OUTS008 { get; set; }
        public string OUTSYSUID { get; set; }
        public string OUTHNAME { get; set; }
        public string OUTDTIME { get; set; }
    }
}
