//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_ERROR
    {
        public int errorid { get; set; }
        public string errorstno { get; set; }
        public string errordate { get; set; }
        public string stuserid { get; set; }
        public string sthostname { get; set; }
        public string sthostip { get; set; }
        public string sthostmac { get; set; }
        public string stmemo { get; set; }
    }
}
