//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_BUKAN
    {
        public int buid { get; set; }
        public string buno { get; set; }
        public string bucounty { get; set; }
        public string budesc { get; set; }
        public string bulev { get; set; }
        public string bucar { get; set; }
        public string bucarno { get; set; }
        public string buprosn { get; set; }
        public string buitem { get; set; }
        public string bumodel { get; set; }
        public string bulot { get; set; }
        public string bumocta { get; set; }
        public string bumocnum { get; set; }
        public string budate { get; set; }
        public string busysuid { get; set; }
        public string buuserid { get; set; }
        public string buhostname { get; set; }
        public string buhostip { get; set; }
        public string buhostmac { get; set; }
        public string bumemo { get; set; }
        public string buudfchar1 { get; set; }
        public string buudfchar2 { get; set; }
        public string buudfchar3 { get; set; }
        public string buudfchar4 { get; set; }
        public Nullable<int> buudfint1 { get; set; }
        public Nullable<int> buudfint2 { get; set; }
        public Nullable<int> buudfint3 { get; set; }
        public Nullable<int> buudfint4 { get; set; }
    }
}
