//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_PRO2PB
    {
        public string pblot { get; set; }
        public string pbmodel { get; set; }
        public string pbitem { get; set; }
        public string pbdate { get; set; }
        public int pbid { get; set; }
        public string pbpcbcode { get; set; }
        public string pbmemo { get; set; }
        public string pbrepair { get; set; }
        public string pbredatea { get; set; }
        public string pbrecodea { get; set; }
        public string pbrenamea { get; set; }
        public string pbngcodea { get; set; }
        public string pbngnamea { get; set; }
        public string pbredateb { get; set; }
        public string pbrecodeb { get; set; }
        public string pbrenameb { get; set; }
        public string pbngcodeb { get; set; }
        public string pbngnameb { get; set; }
        public string pbredatec { get; set; }
        public string pbrecodec { get; set; }
        public string pbrenamec { get; set; }
        public string pbngcodec { get; set; }
        public string pbngnamec { get; set; }
        public string pbudfchar1 { get; set; }
        public string pbudfchar2 { get; set; }
        public string pbudfchar3 { get; set; }
        public string pbudfchar4 { get; set; }
        public Nullable<int> pbudfint1 { get; set; }
        public Nullable<int> pbudfint2 { get; set; }
        public Nullable<int> pbudfint3 { get; set; }
        public Nullable<int> pbudfint4 { get; set; }
    }
}
