//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_INVMB
    {
        public string MB001 { get; set; }
        public string MB002 { get; set; }
        public string MB003 { get; set; }
        public string MB004 { get; set; }
        public string MB005 { get; set; }
        public string MB006 { get; set; }
    }
}
