//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_SCANNER_IN_SUB
    {
        public int ID { get; set; }
        public string INS001 { get; set; }
        public string INS002 { get; set; }
        public string INS003 { get; set; }
        public Nullable<int> INS004 { get; set; }
        public string INS005 { get; set; }
        public string INSYSUID { get; set; }
        public string INHNAME { get; set; }
        public string INDTIME { get; set; }
    }
}
