//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_COUNTRIES
    {
        public int coid { get; set; }
        public string coeng { get; set; }
        public string cochs { get; set; }
        public string cowww { get; set; }
        public string cotel { get; set; }
        public string cotime { get; set; }
        public string memo { get; set; }
    }
}
