//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_SCANNER_IN
    {
        public int ID { get; set; }
        public string IN001 { get; set; }
        public string IN002 { get; set; }
        public string IN003 { get; set; }
        public string IN004 { get; set; }
        public string IN005 { get; set; }
        public Nullable<int> IN006 { get; set; }
        public string INSYSUID { get; set; }
        public string INHNAME { get; set; }
        public string INHIP { get; set; }
        public string INHMAC { get; set; }
        public string INUSER { get; set; }
        public string INDTIME { get; set; }
        public string studfchar1 { get; set; }
        public string studfchar2 { get; set; }
        public string studfchar3 { get; set; }
        public string studfchar4 { get; set; }
        public Nullable<int> studfint1 { get; set; }
        public Nullable<int> studfint2 { get; set; }
        public Nullable<int> studfint3 { get; set; }
        public Nullable<int> studfint4 { get; set; }
    }
}
