//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASSET_LINES
    {
        public int liid { get; set; }
        public string lideptcode { get; set; }
        public string lidept { get; set; }
        public string licode { get; set; }
        public string liname { get; set; }
        public string limemo { get; set; }
        public string liudfchar1 { get; set; }
        public string liudfchar2 { get; set; }
        public string liudfchar3 { get; set; }
        public string liudfchar4 { get; set; }
        public Nullable<int> liudfint1 { get; set; }
        public Nullable<int> liudfint2 { get; set; }
        public Nullable<int> liudfint3 { get; set; }
        public Nullable<int> liudfint4 { get; set; }
    }
}
