//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTASTDTIMESHEET
    {
        public Nullable<System.DateTime> STCREATEDATE { get; set; }
        public string STCREATENAME { get; set; }
        public string STMODEL { get; set; }
        public string STFPHBN { get; set; }
        public string STFPTEXT { get; set; }
        public string STSFPHBN { get; set; }
        public string STSFPTEXT { get; set; }
        public Nullable<decimal> STSMTSHORT { get; set; }
        public Nullable<decimal> STSMT { get; set; }
        public Nullable<decimal> STAISHORT { get; set; }
        public Nullable<decimal> STAI { get; set; }
        public Nullable<decimal> STHI { get; set; }
        public Nullable<decimal> STMODI { get; set; }
        public Nullable<decimal> STPCBSUB { get; set; }
        public Nullable<decimal> STP2DTOTAL { get; set; }
        public Nullable<decimal> STPCBASUB { get; set; }
        public Nullable<decimal> STSUB { get; set; }
        public Nullable<decimal> STASSEMBLY { get; set; }
        public Nullable<decimal> STCHECK { get; set; }
        public Nullable<decimal> STOUTER { get; set; }
        public Nullable<decimal> STINSPECT { get; set; }
        public Nullable<decimal> STPACKING { get; set; }
        public Nullable<decimal> STP1DTOTAL { get; set; }
        public Nullable<decimal> STTOTAL { get; set; }
        public Nullable<decimal> STREAL { get; set; }
        public Nullable<decimal> STYIFEI { get; set; }
        public string STMODINAME { get; set; }
        public Nullable<System.DateTime> STMODIDATE { get; set; }
        public string STUID { get; set; }
        public string STCNAME { get; set; }
        public string STPNAME { get; set; }
        public string STIPADDR { get; set; }
        public string STCOUNT { get; set; }
        public Nullable<decimal> STUDF01 { get; set; }
        public Nullable<decimal> STUDF02 { get; set; }
        public Nullable<decimal> STUDF03 { get; set; }
        public Nullable<decimal> STUDF04 { get; set; }
        public Nullable<decimal> STUDF05 { get; set; }
        public string STUDF51 { get; set; }
        public string STUDF52 { get; set; }
        public string STUDF53 { get; set; }
        public string STUDF54 { get; set; }
        public string STUDF55 { get; set; }
    }
}
