//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ehrinfo
    {
        public string eid { get; set; }
        public string ename { get; set; }
        public string enamec { get; set; }
        public string email { get; set; }
        public string ecorp { get; set; }
        public string edept { get; set; }
    }
}
