//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EISLA
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string LA001 { get; set; }
        public string LA002 { get; set; }
        public Nullable<decimal> LA003 { get; set; }
        public Nullable<decimal> LA004 { get; set; }
        public Nullable<decimal> LA005 { get; set; }
        public Nullable<decimal> LA006 { get; set; }
        public Nullable<decimal> LA007 { get; set; }
        public Nullable<decimal> LA008 { get; set; }
        public Nullable<decimal> LA009 { get; set; }
        public Nullable<decimal> LA010 { get; set; }
        public Nullable<decimal> LA011 { get; set; }
        public Nullable<decimal> LA012 { get; set; }
        public Nullable<decimal> LA013 { get; set; }
        public Nullable<decimal> LA014 { get; set; }
        public Nullable<decimal> LA015 { get; set; }
        public Nullable<decimal> LA016 { get; set; }
        public Nullable<decimal> LA017 { get; set; }
        public Nullable<decimal> LA018 { get; set; }
        public Nullable<decimal> LA019 { get; set; }
        public Nullable<decimal> LA020 { get; set; }
        public Nullable<decimal> LA021 { get; set; }
        public Nullable<decimal> LA022 { get; set; }
        public Nullable<decimal> LA023 { get; set; }
        public Nullable<decimal> LA024 { get; set; }
        public Nullable<decimal> LA025 { get; set; }
        public Nullable<decimal> LA026 { get; set; }
        public Nullable<decimal> LA027 { get; set; }
        public Nullable<decimal> LA028 { get; set; }
        public Nullable<decimal> LA029 { get; set; }
        public Nullable<decimal> LA030 { get; set; }
        public Nullable<decimal> LA031 { get; set; }
        public Nullable<decimal> LA032 { get; set; }
        public Nullable<decimal> LA033 { get; set; }
        public Nullable<decimal> LA034 { get; set; }
        public Nullable<decimal> LA035 { get; set; }
        public Nullable<decimal> LA036 { get; set; }
        public Nullable<decimal> LA037 { get; set; }
        public Nullable<decimal> LA038 { get; set; }
        public Nullable<decimal> LA039 { get; set; }
        public Nullable<decimal> LA040 { get; set; }
        public string LA041 { get; set; }
        public string LA042 { get; set; }
        public string LA043 { get; set; }
        public Nullable<decimal> LA044 { get; set; }
        public Nullable<decimal> LA045 { get; set; }
        public Nullable<decimal> LA046 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
