//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPSMC
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MC001 { get; set; }
        public string MC002 { get; set; }
        public string MC003 { get; set; }
        public string MC004 { get; set; }
        public Nullable<decimal> MC005 { get; set; }
        public Nullable<decimal> MC006 { get; set; }
        public Nullable<decimal> MC007 { get; set; }
        public Nullable<decimal> MC008 { get; set; }
        public Nullable<decimal> MC009 { get; set; }
        public Nullable<decimal> MC010 { get; set; }
        public Nullable<decimal> MC011 { get; set; }
        public string MC012 { get; set; }
        public Nullable<decimal> MC013 { get; set; }
        public Nullable<decimal> MC014 { get; set; }
        public Nullable<decimal> MC015 { get; set; }
        public string MC016 { get; set; }
        public string MC017 { get; set; }
        public string MC018 { get; set; }
        public Nullable<decimal> MC019 { get; set; }
        public Nullable<decimal> MC020 { get; set; }
        public Nullable<decimal> MC021 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
