//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPSTH
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TH001 { get; set; }
        public string TH002 { get; set; }
        public string TH003 { get; set; }
        public string TH004 { get; set; }
        public string TH005 { get; set; }
        public string TH006 { get; set; }
        public string TH007 { get; set; }
        public string TH008 { get; set; }
        public Nullable<decimal> TH009 { get; set; }
        public string TH010 { get; set; }
        public string TH011 { get; set; }
        public Nullable<decimal> TH012 { get; set; }
        public Nullable<decimal> TH013 { get; set; }
        public string TH014 { get; set; }
        public string TH015 { get; set; }
        public Nullable<decimal> TH016 { get; set; }
        public string TH017 { get; set; }
        public string TH018 { get; set; }
        public Nullable<decimal> TH019 { get; set; }
        public Nullable<decimal> TH020 { get; set; }
        public Nullable<decimal> TH021 { get; set; }
        public string TH022 { get; set; }
        public string TH023 { get; set; }
        public Nullable<decimal> TH024 { get; set; }
        public string TH025 { get; set; }
        public string TH026 { get; set; }
        public string TH027 { get; set; }
        public Nullable<decimal> TH028 { get; set; }
        public Nullable<decimal> TH029 { get; set; }
        public Nullable<decimal> TH030 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
