//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQTML
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string ML001 { get; set; }
        public string ML002 { get; set; }
        public string ML003 { get; set; }
        public string ML004 { get; set; }
        public string ML005 { get; set; }
        public string ML006 { get; set; }
        public Nullable<decimal> ML007 { get; set; }
        public Nullable<decimal> ML008 { get; set; }
        public Nullable<decimal> ML009 { get; set; }
        public string ML010 { get; set; }
        public string ML011 { get; set; }
        public Nullable<decimal> ML012 { get; set; }
        public string ML013 { get; set; }
        public string ML014 { get; set; }
        public Nullable<decimal> ML015 { get; set; }
        public string ML016 { get; set; }
        public string ML017 { get; set; }
        public Nullable<decimal> ML018 { get; set; }
        public string ML019 { get; set; }
        public string ML020 { get; set; }
        public string ML021 { get; set; }
        public string ML022 { get; set; }
        public string ML023 { get; set; }
        public string ML024 { get; set; }
        public string ML025 { get; set; }
        public string ML026 { get; set; }
        public string ML027 { get; set; }
        public Nullable<decimal> ML028 { get; set; }
        public Nullable<decimal> ML029 { get; set; }
        public string ML030 { get; set; }
        public string ML031 { get; set; }
        public string ML032 { get; set; }
        public string ML033 { get; set; }
        public Nullable<decimal> ML034 { get; set; }
        public Nullable<decimal> ML035 { get; set; }
        public Nullable<decimal> ML036 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
