//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQTMJ
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MJ001 { get; set; }
        public string MJ002 { get; set; }
        public string MJ003 { get; set; }
        public string MJ004 { get; set; }
        public string MJ005 { get; set; }
        public string MJ006 { get; set; }
        public string MJ007 { get; set; }
        public string MJ008 { get; set; }
        public string MJ009 { get; set; }
        public string MJ010 { get; set; }
        public Nullable<decimal> MJ011 { get; set; }
        public string MJ012 { get; set; }
        public string MJ013 { get; set; }
        public string MJ014 { get; set; }
        public string MJ015 { get; set; }
        public string MJ016 { get; set; }
        public string MJ017 { get; set; }
        public string MJ018 { get; set; }
        public string MJ019 { get; set; }
        public Nullable<decimal> MJ020 { get; set; }
        public Nullable<decimal> MJ021 { get; set; }
        public string MJ022 { get; set; }
        public string MJ023 { get; set; }
        public string MJ024 { get; set; }
        public string MJ025 { get; set; }
        public string MJ026 { get; set; }
        public string MJ027 { get; set; }
        public string MJ028 { get; set; }
        public string MJ029 { get; set; }
        public string MJ030 { get; set; }
        public Nullable<decimal> MJ031 { get; set; }
        public string MJ032 { get; set; }
        public Nullable<decimal> MJ033 { get; set; }
        public string MJ034 { get; set; }
        public string MJ035 { get; set; }
        public Nullable<decimal> MJ036 { get; set; }
        public string MJ037 { get; set; }
        public string MJ038 { get; set; }
        public string MJ039 { get; set; }
        public string MJ040 { get; set; }
        public string MJ041 { get; set; }
        public string MJ042 { get; set; }
        public string MJ043 { get; set; }
        public string MJ044 { get; set; }
        public string MJ045 { get; set; }
        public string MJ046 { get; set; }
        public string MJ047 { get; set; }
        public string MJ048 { get; set; }
        public string MJ049 { get; set; }
        public string MJ050 { get; set; }
        public Nullable<decimal> MJ051 { get; set; }
        public Nullable<decimal> MJ052 { get; set; }
        public Nullable<decimal> MJ053 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
