//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQTTN
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TN001 { get; set; }
        public string TN002 { get; set; }
        public string TN003 { get; set; }
        public string TN004 { get; set; }
        public string TN005 { get; set; }
        public string TN006 { get; set; }
        public string TN007 { get; set; }
        public string TN008 { get; set; }
        public string TN009 { get; set; }
        public string TN010 { get; set; }
        public string TN011 { get; set; }
        public string TN012 { get; set; }
        public string TN013 { get; set; }
        public string TN014 { get; set; }
        public string TN015 { get; set; }
        public string TN016 { get; set; }
        public Nullable<decimal> TN017 { get; set; }
        public Nullable<decimal> TN018 { get; set; }
        public Nullable<decimal> TN019 { get; set; }
        public string TN020 { get; set; }
        public string TN021 { get; set; }
        public string TN022 { get; set; }
        public string TN023 { get; set; }
        public string TN024 { get; set; }
        public string TN025 { get; set; }
        public Nullable<decimal> TN026 { get; set; }
        public Nullable<decimal> TN027 { get; set; }
        public Nullable<decimal> TN028 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
