//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQTTE
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TE001 { get; set; }
        public string TE002 { get; set; }
        public string TE003 { get; set; }
        public string TE004 { get; set; }
        public string TE005 { get; set; }
        public string TE006 { get; set; }
        public Nullable<decimal> TE007 { get; set; }
        public Nullable<decimal> TE008 { get; set; }
        public string TE009 { get; set; }
        public string TE010 { get; set; }
        public string TE011 { get; set; }
        public string TE012 { get; set; }
        public string TE013 { get; set; }
        public string TE014 { get; set; }
        public string TE015 { get; set; }
        public string TE016 { get; set; }
        public string TE017 { get; set; }
        public string TE018 { get; set; }
        public string TE019 { get; set; }
        public string TE020 { get; set; }
        public string TE021 { get; set; }
        public string TE022 { get; set; }
        public string TE023 { get; set; }
        public string TE024 { get; set; }
        public string TE025 { get; set; }
        public string TE026 { get; set; }
        public string TE027 { get; set; }
        public string TE028 { get; set; }
        public string TE029 { get; set; }
        public string TE030 { get; set; }
        public string TE031 { get; set; }
        public string TE032 { get; set; }
        public string TE033 { get; set; }
        public string TE034 { get; set; }
        public Nullable<decimal> TE035 { get; set; }
        public Nullable<decimal> TE036 { get; set; }
        public Nullable<decimal> TE037 { get; set; }
        public Nullable<decimal> TE038 { get; set; }
        public string TE039 { get; set; }
        public Nullable<decimal> TE040 { get; set; }
        public Nullable<decimal> TE041 { get; set; }
        public string TE042 { get; set; }
        public string TE043 { get; set; }
        public string TE044 { get; set; }
        public Nullable<decimal> TE045 { get; set; }
        public string TE046 { get; set; }
        public string TE047 { get; set; }
        public string TE048 { get; set; }
        public string TE049 { get; set; }
        public string TE050 { get; set; }
        public string TE051 { get; set; }
        public Nullable<decimal> TE052 { get; set; }
        public Nullable<decimal> TE053 { get; set; }
        public Nullable<decimal> TE054 { get; set; }
        public Nullable<decimal> TE055 { get; set; }
        public string TE056 { get; set; }
        public string TE057 { get; set; }
        public string TE058 { get; set; }
        public string TE059 { get; set; }
        public string TE060 { get; set; }
        public string TE061 { get; set; }
        public Nullable<decimal> TE062 { get; set; }
        public Nullable<decimal> TE063 { get; set; }
        public Nullable<decimal> TE064 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
