//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelPrice
    {
        public string TL004 { get; set; }
        public string MA002 { get; set; }
        public string MB001 { get; set; }
        public string MB002 { get; set; }
        public string dtaMB080 { get; set; }
        public string dtaTM014 { get; set; }
        public string dtaTL005 { get; set; }
        public Nullable<decimal> dtaTM010 { get; set; }
        public Nullable<decimal> dtaMB039 { get; set; }
        public Nullable<decimal> dtaMB036 { get; set; }
    }
}
