//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GFCTD
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TD001 { get; set; }
        public string TD002 { get; set; }
        public string TD003 { get; set; }
        public string TD004 { get; set; }
        public Nullable<decimal> TD005 { get; set; }
        public string TD006 { get; set; }
        public string TD007 { get; set; }
        public string TD008 { get; set; }
        public Nullable<decimal> TD009 { get; set; }
        public Nullable<decimal> TD010 { get; set; }
        public string TD011 { get; set; }
        public string TD012 { get; set; }
        public string TD013 { get; set; }
        public Nullable<decimal> TD014 { get; set; }
        public Nullable<decimal> TD015 { get; set; }
        public Nullable<decimal> TD016 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
