//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GMPTF
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TF001 { get; set; }
        public string TF002 { get; set; }
        public string TF003 { get; set; }
        public string TF004 { get; set; }
        public string TF005 { get; set; }
        public string TF006 { get; set; }
        public string TF007 { get; set; }
        public string TF008 { get; set; }
        public string TF009 { get; set; }
        public string TF010 { get; set; }
        public string TF011 { get; set; }
        public string TF012 { get; set; }
        public string TF013 { get; set; }
        public string TF014 { get; set; }
        public string TF015 { get; set; }
        public string TF016 { get; set; }
        public string TF017 { get; set; }
        public string TF018 { get; set; }
        public string TF019 { get; set; }
        public string TF020 { get; set; }
        public string TF021 { get; set; }
        public string TF022 { get; set; }
        public string TF023 { get; set; }
        public string TF024 { get; set; }
        public string TF025 { get; set; }
        public string TF026 { get; set; }
        public string TF027 { get; set; }
        public string TF028 { get; set; }
        public string TF029 { get; set; }
        public string TF030 { get; set; }
        public string TF031 { get; set; }
        public string TF032 { get; set; }
        public string TF033 { get; set; }
        public string TF034 { get; set; }
        public string TF035 { get; set; }
        public string TF036 { get; set; }
        public string TF037 { get; set; }
        public Nullable<decimal> TF038 { get; set; }
        public Nullable<decimal> TF039 { get; set; }
        public string TF040 { get; set; }
        public string TF041 { get; set; }
        public string TF042 { get; set; }
        public string TF043 { get; set; }
        public Nullable<decimal> TF044 { get; set; }
        public Nullable<decimal> TF045 { get; set; }
        public Nullable<decimal> TF046 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
