//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSPTM
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TM001 { get; set; }
        public string TM002 { get; set; }
        public string TM003 { get; set; }
        public string TM004 { get; set; }
        public string TM005 { get; set; }
        public string TM006 { get; set; }
        public string TM007 { get; set; }
        public Nullable<decimal> TM008 { get; set; }
        public string TM009 { get; set; }
        public string TM010 { get; set; }
        public string TM011 { get; set; }
        public string TM012 { get; set; }
        public string TM013 { get; set; }
        public string TM014 { get; set; }
        public string TM015 { get; set; }
        public string TM016 { get; set; }
        public string TM017 { get; set; }
        public string TM018 { get; set; }
        public string TM019 { get; set; }
        public string TM020 { get; set; }
        public string TM021 { get; set; }
        public string TM022 { get; set; }
        public Nullable<decimal> TM023 { get; set; }
        public Nullable<decimal> TM024 { get; set; }
        public string TM025 { get; set; }
        public string TM026 { get; set; }
        public string TM027 { get; set; }
        public string TM028 { get; set; }
        public string TM029 { get; set; }
        public string TM030 { get; set; }
        public string TM031 { get; set; }
        public string TM032 { get; set; }
        public string TM033 { get; set; }
        public Nullable<decimal> TM034 { get; set; }
        public Nullable<decimal> TM035 { get; set; }
        public Nullable<decimal> TM036 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
