//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRSTX
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TX001 { get; set; }
        public string TX002 { get; set; }
        public string TX003 { get; set; }
        public string TX004 { get; set; }
        public string TX005 { get; set; }
        public string TX006 { get; set; }
        public Nullable<decimal> TX007 { get; set; }
        public Nullable<decimal> TX008 { get; set; }
        public string TX009 { get; set; }
        public string TX010 { get; set; }
        public string TX011 { get; set; }
        public string TX012 { get; set; }
        public string TX013 { get; set; }
        public string TX014 { get; set; }
        public string TX015 { get; set; }
        public string TX016 { get; set; }
        public string TX017 { get; set; }
        public string TX018 { get; set; }
        public string TX019 { get; set; }
        public string TX020 { get; set; }
        public string TX021 { get; set; }
        public string TX022 { get; set; }
        public string TX023 { get; set; }
        public string TX024 { get; set; }
        public string TX025 { get; set; }
        public string TX026 { get; set; }
        public string TX027 { get; set; }
        public string TX104 { get; set; }
        public string TX105 { get; set; }
        public string TX106 { get; set; }
        public Nullable<decimal> TX107 { get; set; }
        public Nullable<decimal> TX108 { get; set; }
        public string TX109 { get; set; }
        public string TX110 { get; set; }
        public string TX111 { get; set; }
        public string TX112 { get; set; }
        public string TX113 { get; set; }
        public string TX114 { get; set; }
        public string TX115 { get; set; }
        public string TX116 { get; set; }
        public string TX117 { get; set; }
        public string TX118 { get; set; }
        public string TX119 { get; set; }
        public string TX120 { get; set; }
        public string TX122 { get; set; }
        public string TX123 { get; set; }
        public string TX124 { get; set; }
        public string TX125 { get; set; }
        public string TX126 { get; set; }
        public string TX028 { get; set; }
        public string TX029 { get; set; }
        public string TX030 { get; set; }
        public Nullable<decimal> TX031 { get; set; }
        public Nullable<decimal> TX032 { get; set; }
        public Nullable<decimal> TX033 { get; set; }
        public string TX127 { get; set; }
        public string TX128 { get; set; }
        public string TX129 { get; set; }
        public Nullable<decimal> TX130 { get; set; }
        public Nullable<decimal> TX131 { get; set; }
        public Nullable<decimal> TX132 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
