//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRSTV
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TV001 { get; set; }
        public string TV002 { get; set; }
        public string TV003 { get; set; }
        public string TV004 { get; set; }
        public string TV005 { get; set; }
        public Nullable<decimal> TV006 { get; set; }
        public Nullable<decimal> TV007 { get; set; }
        public string TV008 { get; set; }
        public string TV009 { get; set; }
        public string TV010 { get; set; }
        public string TV011 { get; set; }
        public string TV012 { get; set; }
        public string TV013 { get; set; }
        public string TV014 { get; set; }
        public string TV015 { get; set; }
        public string TV016 { get; set; }
        public string TV017 { get; set; }
        public string TV018 { get; set; }
        public string TV019 { get; set; }
        public string TV020 { get; set; }
        public string TV021 { get; set; }
        public string TV022 { get; set; }
        public string TV023 { get; set; }
        public string TV024 { get; set; }
        public string TV025 { get; set; }
        public Nullable<decimal> TV026 { get; set; }
        public Nullable<decimal> TV027 { get; set; }
        public string TV028 { get; set; }
        public string TV029 { get; set; }
        public string TV030 { get; set; }
        public Nullable<decimal> TV031 { get; set; }
        public Nullable<decimal> TV032 { get; set; }
        public Nullable<decimal> TV033 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
