//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRSTJ
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TJ001 { get; set; }
        public string TJ002 { get; set; }
        public string TJ003 { get; set; }
        public string TJ004 { get; set; }
        public string TJ005 { get; set; }
        public string TJ006 { get; set; }
        public string TJ007 { get; set; }
        public string TJ008 { get; set; }
        public Nullable<decimal> TJ009 { get; set; }
        public string TJ010 { get; set; }
        public string TJ011 { get; set; }
        public string TJ012 { get; set; }
        public string TJ013 { get; set; }
        public string TJ014 { get; set; }
        public string TJ015 { get; set; }
        public Nullable<decimal> TJ016 { get; set; }
        public string TJ017 { get; set; }
        public string TJ018 { get; set; }
        public string TJ019 { get; set; }
        public string TJ020 { get; set; }
        public string TJ021 { get; set; }
        public string TJ022 { get; set; }
        public string TJ023 { get; set; }
        public string TJ024 { get; set; }
        public string TJ025 { get; set; }
        public Nullable<decimal> TJ026 { get; set; }
        public string TJ027 { get; set; }
        public Nullable<decimal> TJ028 { get; set; }
        public string TJ029 { get; set; }
        public string TJ030 { get; set; }
        public string TJ031 { get; set; }
        public string TJ032 { get; set; }
        public string TJ033 { get; set; }
        public string TJ034 { get; set; }
        public string TJ035 { get; set; }
        public string TJ036 { get; set; }
        public string TJ037 { get; set; }
        public string TJ038 { get; set; }
        public string TJ039 { get; set; }
        public string TJ040 { get; set; }
        public string TJ041 { get; set; }
        public Nullable<decimal> TJ042 { get; set; }
        public string TJ043 { get; set; }
        public string TJ044 { get; set; }
        public string TJ045 { get; set; }
        public string TJ046 { get; set; }
        public string TJ047 { get; set; }
        public string TJ048 { get; set; }
        public string TJ049 { get; set; }
        public string TJ050 { get; set; }
        public string TJ051 { get; set; }
        public string TJ052 { get; set; }
        public Nullable<decimal> TJ053 { get; set; }
        public string TJ054 { get; set; }
        public string TJ055 { get; set; }
        public string TJ056 { get; set; }
        public string TJ057 { get; set; }
        public string TJ058 { get; set; }
        public string TJ059 { get; set; }
        public string TJ060 { get; set; }
        public string TJ061 { get; set; }
        public string TJ062 { get; set; }
        public string TJ063 { get; set; }
        public string TJ064 { get; set; }
        public Nullable<decimal> TJ065 { get; set; }
        public Nullable<decimal> TJ066 { get; set; }
        public Nullable<decimal> TJ067 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
