//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSR3BOM
    {
        public string BOMHBN { get; set; }
        public string BOMLEVEL { get; set; }
        public string BOMENGNO { get; set; }
        public string PARTSPROPERTIES { get; set; }
        public string VARIETY { get; set; }
        public string BOMPROCESS { get; set; }
        public string BOMPLACE { get; set; }
        public string BOMITEM { get; set; }
        public string BOMPARTS { get; set; }
        public Nullable<decimal> COMPONENT { get; set; }
        public string SUPPLIER { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> STDPRICE { get; set; }
        public Nullable<decimal> STDAMOUNT { get; set; }
        public Nullable<decimal> LASTPRICE { get; set; }
        public Nullable<decimal> LASTAMOUNT { get; set; }
        public Nullable<decimal> STOCK { get; set; }
        public Nullable<decimal> STOCKAMOUNT { get; set; }
        public string PURCHASER { get; set; }
        public string PARTSNAME { get; set; }
        public Nullable<decimal> LEADTIME { get; set; }
        public Nullable<decimal> MOQ { get; set; }
        public string MANUFACTURER { get; set; }
        public string MAKER { get; set; }
        public string MAKERITEM { get; set; }
        public string PURCHASEREGIONAL { get; set; }
        public string MATERIALTYPE { get; set; }
        public string バルク品目 { get; set; }
        public string 原価計算関連フラグ { get; set; }
    }
}
