//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTLK
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string LK001 { get; set; }
        public string LK002 { get; set; }
        public string LK003 { get; set; }
        public string LK004 { get; set; }
        public string LK005 { get; set; }
        public string LK006 { get; set; }
        public string LK007 { get; set; }
        public string LK008 { get; set; }
        public Nullable<decimal> LK009 { get; set; }
        public string LK010 { get; set; }
        public string LK011 { get; set; }
        public string LK012 { get; set; }
        public Nullable<decimal> LK013 { get; set; }
        public string LK014 { get; set; }
        public string LK015 { get; set; }
        public string LK016 { get; set; }
        public string LK017 { get; set; }
        public string LK018 { get; set; }
        public string LK019 { get; set; }
        public string LK020 { get; set; }
        public Nullable<decimal> LK021 { get; set; }
        public Nullable<decimal> LK022 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
