//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVLD
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string LD001 { get; set; }
        public string LD002 { get; set; }
        public string LD003 { get; set; }
        public decimal LD004 { get; set; }
        public string LD005 { get; set; }
        public string LD006 { get; set; }
        public string LD007 { get; set; }
        public string LD008 { get; set; }
        public string LD009 { get; set; }
        public Nullable<decimal> LD010 { get; set; }
        public Nullable<decimal> LD011 { get; set; }
        public Nullable<decimal> LD012 { get; set; }
        public string LD013 { get; set; }
        public Nullable<decimal> LD014 { get; set; }
        public string LD015 { get; set; }
        public string LD016 { get; set; }
        public string LD017 { get; set; }
        public Nullable<decimal> LD018 { get; set; }
        public Nullable<decimal> LD019 { get; set; }
        public Nullable<decimal> LD020 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
