//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVLE
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string LE001 { get; set; }
        public string LE002 { get; set; }
        public string LE003 { get; set; }
        public string LE004 { get; set; }
        public string LE005 { get; set; }
        public Nullable<decimal> LE006 { get; set; }
        public Nullable<decimal> LE007 { get; set; }
        public Nullable<decimal> LE008 { get; set; }
        public Nullable<decimal> LE009 { get; set; }
        public Nullable<decimal> LE010 { get; set; }
        public Nullable<decimal> LE011 { get; set; }
        public Nullable<decimal> LE012 { get; set; }
        public Nullable<decimal> LE013 { get; set; }
        public Nullable<decimal> LE014 { get; set; }
        public Nullable<decimal> LE015 { get; set; }
        public Nullable<decimal> LE016 { get; set; }
        public Nullable<decimal> LE017 { get; set; }
        public Nullable<decimal> LE018 { get; set; }
        public Nullable<decimal> LE019 { get; set; }
        public Nullable<decimal> LE020 { get; set; }
        public Nullable<decimal> LE021 { get; set; }
        public Nullable<decimal> LE022 { get; set; }
        public Nullable<decimal> LE023 { get; set; }
        public Nullable<decimal> LE024 { get; set; }
        public Nullable<decimal> LE025 { get; set; }
        public Nullable<decimal> LE026 { get; set; }
        public Nullable<decimal> LE027 { get; set; }
        public Nullable<decimal> LE028 { get; set; }
        public Nullable<decimal> LE029 { get; set; }
        public Nullable<decimal> LE030 { get; set; }
        public Nullable<decimal> LE031 { get; set; }
        public Nullable<decimal> LE032 { get; set; }
        public Nullable<decimal> LE033 { get; set; }
        public Nullable<decimal> LE034 { get; set; }
        public Nullable<decimal> LE035 { get; set; }
        public Nullable<decimal> LE036 { get; set; }
        public Nullable<decimal> LE037 { get; set; }
        public Nullable<decimal> LE038 { get; set; }
        public Nullable<decimal> LE039 { get; set; }
        public Nullable<decimal> LE040 { get; set; }
        public Nullable<decimal> LE041 { get; set; }
        public Nullable<decimal> LE042 { get; set; }
        public string LE043 { get; set; }
        public string LE044 { get; set; }
        public string LE045 { get; set; }
        public Nullable<decimal> LE046 { get; set; }
        public Nullable<decimal> LE047 { get; set; }
        public Nullable<decimal> LE048 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
