//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVLF
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string LF001 { get; set; }
        public string LF002 { get; set; }
        public Nullable<decimal> LF003 { get; set; }
        public Nullable<decimal> LF004 { get; set; }
        public string LF005 { get; set; }
        public string LF006 { get; set; }
        public string LF007 { get; set; }
        public Nullable<decimal> LF008 { get; set; }
        public Nullable<decimal> LF009 { get; set; }
        public Nullable<decimal> LF010 { get; set; }
        public Nullable<decimal> LF011 { get; set; }
        public Nullable<decimal> LF012 { get; set; }
        public Nullable<decimal> LF013 { get; set; }
        public string LF014 { get; set; }
        public string LF015 { get; set; }
        public string LF016 { get; set; }
        public string LF017 { get; set; }
        public string LF018 { get; set; }
        public string LF019 { get; set; }
        public Nullable<decimal> LF020 { get; set; }
        public Nullable<decimal> LF021 { get; set; }
        public Nullable<decimal> LF022 { get; set; }
        public Nullable<decimal> LF023 { get; set; }
        public string LF024 { get; set; }
        public string LF025 { get; set; }
        public string LF026 { get; set; }
        public Nullable<decimal> LF027 { get; set; }
        public Nullable<decimal> LF028 { get; set; }
        public Nullable<decimal> LF029 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
