//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVME
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string ME001 { get; set; }
        public string ME002 { get; set; }
        public string ME003 { get; set; }
        public string ME004 { get; set; }
        public string ME005 { get; set; }
        public string ME006 { get; set; }
        public string ME007 { get; set; }
        public string ME008 { get; set; }
        public string ME009 { get; set; }
        public string ME010 { get; set; }
        public string ME011 { get; set; }
        public string ME012 { get; set; }
        public string ME013 { get; set; }
        public string ME014 { get; set; }
        public string ME015 { get; set; }
        public string ME016 { get; set; }
        public string ME017 { get; set; }
        public string ME018 { get; set; }
        public string ME019 { get; set; }
        public string ME020 { get; set; }
        public string ME021 { get; set; }
        public string ME022 { get; set; }
        public Nullable<decimal> ME023 { get; set; }
        public string ME024 { get; set; }
        public string ME025 { get; set; }
        public string ME026 { get; set; }
        public Nullable<decimal> ME027 { get; set; }
        public Nullable<decimal> ME028 { get; set; }
        public Nullable<decimal> ME029 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
