//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPSTC
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TC001 { get; set; }
        public string TC002 { get; set; }
        public string TC003 { get; set; }
        public string TC004 { get; set; }
        public string TC005 { get; set; }
        public string TC006 { get; set; }
        public string TC007 { get; set; }
        public string TC008 { get; set; }
        public string TC009 { get; set; }
        public string TC010 { get; set; }
        public Nullable<decimal> TC011 { get; set; }
        public Nullable<decimal> TC012 { get; set; }
        public Nullable<decimal> TC013 { get; set; }
        public Nullable<decimal> TC014 { get; set; }
        public Nullable<decimal> TC015 { get; set; }
        public Nullable<decimal> TC016 { get; set; }
        public Nullable<decimal> TC017 { get; set; }
        public Nullable<decimal> TC018 { get; set; }
        public Nullable<decimal> TC019 { get; set; }
        public Nullable<decimal> TC020 { get; set; }
        public Nullable<decimal> TC021 { get; set; }
        public Nullable<decimal> TC022 { get; set; }
        public Nullable<decimal> TC023 { get; set; }
        public Nullable<decimal> TC024 { get; set; }
        public Nullable<decimal> TC111 { get; set; }
        public Nullable<decimal> TC112 { get; set; }
        public Nullable<decimal> TC113 { get; set; }
        public Nullable<decimal> TC114 { get; set; }
        public Nullable<decimal> TC115 { get; set; }
        public Nullable<decimal> TC116 { get; set; }
        public Nullable<decimal> TC117 { get; set; }
        public Nullable<decimal> TC118 { get; set; }
        public Nullable<decimal> TC119 { get; set; }
        public Nullable<decimal> TC120 { get; set; }
        public Nullable<decimal> TC121 { get; set; }
        public Nullable<decimal> TC122 { get; set; }
        public Nullable<decimal> TC123 { get; set; }
        public Nullable<decimal> TC124 { get; set; }
        public Nullable<decimal> TC125 { get; set; }
        public string TC025 { get; set; }
        public string TC026 { get; set; }
        public string TC027 { get; set; }
        public Nullable<decimal> TC028 { get; set; }
        public string TC029 { get; set; }
        public string TC030 { get; set; }
        public string TC031 { get; set; }
        public Nullable<decimal> TC032 { get; set; }
        public Nullable<decimal> TC033 { get; set; }
        public Nullable<decimal> TC034 { get; set; }
        public string TC126 { get; set; }
        public string TC127 { get; set; }
        public string TC128 { get; set; }
        public Nullable<decimal> TC129 { get; set; }
        public Nullable<decimal> TC130 { get; set; }
        public Nullable<decimal> TC131 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
