//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPSTG
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TG001 { get; set; }
        public string TG002 { get; set; }
        public string TG003 { get; set; }
        public string TG004 { get; set; }
        public string TG005 { get; set; }
        public string TG006 { get; set; }
        public string TG007 { get; set; }
        public string TG008 { get; set; }
        public string TG009 { get; set; }
        public string TG010 { get; set; }
        public string TG011 { get; set; }
        public string TG012 { get; set; }
        public string TG013 { get; set; }
        public string TG014 { get; set; }
        public string TG015 { get; set; }
        public string TG016 { get; set; }
        public string TG017 { get; set; }
        public Nullable<decimal> TG018 { get; set; }
        public Nullable<decimal> TG019 { get; set; }
        public Nullable<decimal> TG020 { get; set; }
        public Nullable<decimal> TG021 { get; set; }
        public Nullable<decimal> TG022 { get; set; }
        public Nullable<decimal> TG023 { get; set; }
        public Nullable<decimal> TG024 { get; set; }
        public Nullable<decimal> TG025 { get; set; }
        public Nullable<decimal> TG026 { get; set; }
        public string TG027 { get; set; }
        public string TG028 { get; set; }
        public string TG029 { get; set; }
        public Nullable<decimal> TG030 { get; set; }
        public Nullable<decimal> TG031 { get; set; }
        public Nullable<decimal> TG032 { get; set; }
        public Nullable<decimal> TG033 { get; set; }
        public Nullable<decimal> TG034 { get; set; }
        public Nullable<decimal> TG035 { get; set; }
        public string TG036 { get; set; }
        public string TG037 { get; set; }
        public string TG038 { get; set; }
        public Nullable<decimal> TG039 { get; set; }
        public Nullable<decimal> TG040 { get; set; }
        public string TG041 { get; set; }
        public string TG042 { get; set; }
        public string TG043 { get; set; }
        public string TG044 { get; set; }
        public string TG045 { get; set; }
        public string TG046 { get; set; }
        public string TG047 { get; set; }
        public string TG048 { get; set; }
        public Nullable<decimal> TG049 { get; set; }
        public string TG050 { get; set; }
        public string TG051 { get; set; }
        public string TG052 { get; set; }
        public Nullable<decimal> TG053 { get; set; }
        public Nullable<decimal> TG054 { get; set; }
        public Nullable<decimal> TG055 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
