//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPSTI
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TI001 { get; set; }
        public string TI002 { get; set; }
        public string TI003 { get; set; }
        public string TI004 { get; set; }
        public string TI005 { get; set; }
        public string TI006 { get; set; }
        public string TI007 { get; set; }
        public string TI008 { get; set; }
        public string TI009 { get; set; }
        public string TI010 { get; set; }
        public string TI011 { get; set; }
        public string TI012 { get; set; }
        public string TI013 { get; set; }
        public Nullable<decimal> TI014 { get; set; }
        public Nullable<decimal> TI015 { get; set; }
        public string TI016 { get; set; }
        public Nullable<decimal> TI017 { get; set; }
        public Nullable<decimal> TI018 { get; set; }
        public string TI019 { get; set; }
        public Nullable<decimal> TI020 { get; set; }
        public string TI021 { get; set; }
        public Nullable<decimal> TI022 { get; set; }
        public Nullable<decimal> TI023 { get; set; }
        public string TI024 { get; set; }
        public string TI025 { get; set; }
        public string TI026 { get; set; }
        public Nullable<decimal> TI027 { get; set; }
        public Nullable<decimal> TI028 { get; set; }
        public Nullable<decimal> TI029 { get; set; }
        public Nullable<decimal> TI030 { get; set; }
        public string TI031 { get; set; }
        public Nullable<decimal> TI032 { get; set; }
        public string TI033 { get; set; }
        public string TI034 { get; set; }
        public string TI035 { get; set; }
        public string TI036 { get; set; }
        public Nullable<decimal> TI037 { get; set; }
        public Nullable<decimal> TI038 { get; set; }
        public Nullable<decimal> TI039 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
