//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Nullable<int> INum { get; set; }
        public string IPage { get; set; }
        public string IDevice { get; set; }
        public string IGroup { get; set; }
        public string IField { get; set; }
        public string IValue { get; set; }
        public Nullable<int> IIcon { get; set; }
        public Nullable<int> IID { get; set; }
        public int ReportID { get; set; }
    }
}
