//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lean_Board
    {
        public int lb_Guid { get; set; }
        public System.DateTime lb_StartDate { get; set; }
        public System.DateTime lb_EndDate { get; set; }
        public string lb_CompanyName { get; set; }
        public string lb_Visitors { get; set; }
    }
}
