//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeanSerial_Entities : DbContext
    {
        public LeanSerial_Entities()
            : base("name=LeanSerial_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP_PREVIEW> APP_PREVIEW { get; set; }
        public virtual DbSet<APP_PREVIEW_TYPE> APP_PREVIEW_TYPE { get; set; }
        public virtual DbSet<DTABOM_modelindex> DTABOM_modelindex { get; set; }
        public virtual DbSet<DTABOM_tablelist> DTABOM_tablelist { get; set; }
        public virtual DbSet<DTAREALTIMESHEET> DTAREALTIMESHEET { get; set; }
        public virtual DbSet<DTASSET_BUKAN> DTASSET_BUKAN { get; set; }
        public virtual DbSet<DTASSET_CHINA> DTASSET_CHINA { get; set; }
        public virtual DbSet<DTASSET_CHINAC> DTASSET_CHINAC { get; set; }
        public virtual DbSet<DTASSET_COPTA> DTASSET_COPTA { get; set; }
        public virtual DbSet<DTASSET_COPTB> DTASSET_COPTB { get; set; }
        public virtual DbSet<DTASSET_COUNTRIES> DTASSET_COUNTRIES { get; set; }
        public virtual DbSet<DTASSET_DAYS> DTASSET_DAYS { get; set; }
        public virtual DbSet<DTASSET_ERROR> DTASSET_ERROR { get; set; }
        public virtual DbSet<DTASSET_EVERYBAK> DTASSET_EVERYBAK { get; set; }
        public virtual DbSet<DTASSET_LINES> DTASSET_LINES { get; set; }
        public virtual DbSet<DTASSET_PORT> DTASSET_PORT { get; set; }
        public virtual DbSet<DTASSET_PREVIEW> DTASSET_PREVIEW { get; set; }
        public virtual DbSet<DTASSET_PRO1PA> DTASSET_PRO1PA { get; set; }
        public virtual DbSet<DTASSET_PRO1PB> DTASSET_PRO1PB { get; set; }
        public virtual DbSet<DTASSET_PRO2PA> DTASSET_PRO2PA { get; set; }
        public virtual DbSet<DTASSET_PRO2PB> DTASSET_PRO2PB { get; set; }
        public virtual DbSet<DTASSET_SCANNER_ALL> DTASSET_SCANNER_ALL { get; set; }
        public virtual DbSet<DTASSET_SCANNER_IN> DTASSET_SCANNER_IN { get; set; }
        public virtual DbSet<DTASSET_SCANNER_IN_SUB> DTASSET_SCANNER_IN_SUB { get; set; }
        public virtual DbSet<DTASSET_SCANNER_OUT> DTASSET_SCANNER_OUT { get; set; }
        public virtual DbSet<DTASSET_SCANNER_OUT_SUB> DTASSET_SCANNER_OUT_SUB { get; set; }
        public virtual DbSet<DTASSET_SCANNER_UP> DTASSET_SCANNER_UP { get; set; }
        public virtual DbSet<DTASSET_STOCK> DTASSET_STOCK { get; set; }
        public virtual DbSet<DTASSET_STOCK_INOUT> DTASSET_STOCK_INOUT { get; set; }
        public virtual DbSet<DTASSET_TIMING> DTASSET_TIMING { get; set; }
        public virtual DbSet<DTASSET_USER> DTASSET_USER { get; set; }
        public virtual DbSet<DTASSET_USERLOG> DTASSET_USERLOG { get; set; }
        public virtual DbSet<DTASSET_WELCOME> DTASSET_WELCOME { get; set; }
        public virtual DbSet<DTASTDTIMESHEET> DTASTDTIMESHEET { get; set; }
        public virtual DbSet<ehrinfo> ehrinfo { get; set; }
        public virtual DbSet<Lean_Board> Lean_Board { get; set; }
        public virtual DbSet<DETAILPLAN> DETAILPLAN { get; set; }
        public virtual DbSet<DTABOM_bomupdatetime> DTABOM_bomupdatetime { get; set; }
        public virtual DbSet<DTABOM_modelcategory> DTABOM_modelcategory { get; set; }
        public virtual DbSet<DTABOM_ModeltoParts> DTABOM_ModeltoParts { get; set; }
        public virtual DbSet<DTASSET_FIELD> DTASSET_FIELD { get; set; }
        public virtual DbSet<DTASSET_INVLB> DTASSET_INVLB { get; set; }
        public virtual DbSet<DTASSET_INVMB> DTASSET_INVMB { get; set; }
        public virtual DbSet<DTASSET_INVXB> DTASSET_INVXB { get; set; }
        public virtual DbSet<DTASSET_SHIP> DTASSET_SHIP { get; set; }
        public virtual DbSet<DTASSET_SHIPA> DTASSET_SHIPA { get; set; }
        public virtual DbSet<DTASSET_SHIPINV> DTASSET_SHIPINV { get; set; }
        public virtual DbSet<DTASSET_SYOKA> DTASSET_SYOKA { get; set; }
        public virtual DbSet<DTASSET_SYOKAA> DTASSET_SYOKAA { get; set; }
        public virtual DbSet<HDATA> HDATA { get; set; }
        public virtual DbSet<INSR3BOM> INSR3BOM { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<MODEL_ST> MODEL_ST { get; set; }
        public virtual DbSet<ModelBOM> ModelBOM { get; set; }
        public virtual DbSet<OPHLOG> OPHLOG { get; set; }
        public virtual DbSet<R3BOM> R3BOM { get; set; }
    }
}
