//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOCTO
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TO001 { get; set; }
        public string TO002 { get; set; }
        public string TO003 { get; set; }
        public string TO004 { get; set; }
        public string TO005 { get; set; }
        public string TO006 { get; set; }
        public string TO007 { get; set; }
        public string TO008 { get; set; }
        public string TO009 { get; set; }
        public string TO010 { get; set; }
        public string TO011 { get; set; }
        public string TO012 { get; set; }
        public string TO013 { get; set; }
        public string TO014 { get; set; }
        public string TO015 { get; set; }
        public string TO016 { get; set; }
        public Nullable<decimal> TO017 { get; set; }
        public Nullable<decimal> TO018 { get; set; }
        public Nullable<decimal> TO019 { get; set; }
        public Nullable<decimal> TO020 { get; set; }
        public string TO021 { get; set; }
        public string TO022 { get; set; }
        public string TO023 { get; set; }
        public Nullable<decimal> TO024 { get; set; }
        public string TO025 { get; set; }
        public string TO026 { get; set; }
        public string TO027 { get; set; }
        public string TO028 { get; set; }
        public string TO029 { get; set; }
        public string TO030 { get; set; }
        public string TO031 { get; set; }
        public string TO032 { get; set; }
        public string TO033 { get; set; }
        public string TO034 { get; set; }
        public string TO035 { get; set; }
        public string TO036 { get; set; }
        public string TO037 { get; set; }
        public string TO038 { get; set; }
        public string TO039 { get; set; }
        public string TO040 { get; set; }
        public string TO041 { get; set; }
        public Nullable<decimal> TO042 { get; set; }
        public string TO043 { get; set; }
        public string TO044 { get; set; }
        public string TO045 { get; set; }
        public Nullable<decimal> TO046 { get; set; }
        public string TO047 { get; set; }
        public Nullable<decimal> TO048 { get; set; }
        public Nullable<decimal> TO049 { get; set; }
        public Nullable<decimal> TO050 { get; set; }
        public string TO051 { get; set; }
        public string TO052 { get; set; }
        public string TO106 { get; set; }
        public string TO107 { get; set; }
        public string TO108 { get; set; }
        public string TO109 { get; set; }
        public string TO110 { get; set; }
        public string TO111 { get; set; }
        public string TO112 { get; set; }
        public string TO113 { get; set; }
        public string TO114 { get; set; }
        public string TO115 { get; set; }
        public string TO116 { get; set; }
        public Nullable<decimal> TO117 { get; set; }
        public Nullable<decimal> TO118 { get; set; }
        public Nullable<decimal> TO119 { get; set; }
        public Nullable<decimal> TO120 { get; set; }
        public string TO121 { get; set; }
        public string TO122 { get; set; }
        public string TO123 { get; set; }
        public Nullable<decimal> TO124 { get; set; }
        public string TO125 { get; set; }
        public string TO126 { get; set; }
        public string TO127 { get; set; }
        public string TO128 { get; set; }
        public string TO129 { get; set; }
        public string TO130 { get; set; }
        public string TO131 { get; set; }
        public string TO132 { get; set; }
        public string TO133 { get; set; }
        public string TO134 { get; set; }
        public string TO135 { get; set; }
        public string TO136 { get; set; }
        public string TO137 { get; set; }
        public string TO138 { get; set; }
        public string TO139 { get; set; }
        public string TO140 { get; set; }
        public string TO145 { get; set; }
        public Nullable<decimal> TO146 { get; set; }
        public string TO147 { get; set; }
        public Nullable<decimal> TO148 { get; set; }
        public Nullable<decimal> TO149 { get; set; }
        public Nullable<decimal> TO150 { get; set; }
        public string TO151 { get; set; }
        public Nullable<decimal> TO053 { get; set; }
        public string TO054 { get; set; }
        public string TO154 { get; set; }
        public Nullable<decimal> TO055 { get; set; }
        public Nullable<decimal> TO155 { get; set; }
        public string TO056 { get; set; }
        public string TO156 { get; set; }
        public string TO057 { get; set; }
        public string TO157 { get; set; }
        public string TO058 { get; set; }
        public string TO158 { get; set; }
        public Nullable<decimal> TO059 { get; set; }
        public Nullable<decimal> TO159 { get; set; }
        public Nullable<decimal> TO060 { get; set; }
        public Nullable<decimal> TO160 { get; set; }
        public Nullable<decimal> TO061 { get; set; }
        public Nullable<decimal> TO161 { get; set; }
        public string TO062 { get; set; }
        public string TO162 { get; set; }
        public string TO063 { get; set; }
        public string TO064 { get; set; }
        public string TO065 { get; set; }
        public Nullable<decimal> TO066 { get; set; }
        public Nullable<decimal> TO067 { get; set; }
        public Nullable<decimal> TO068 { get; set; }
        public string TO163 { get; set; }
        public string TO164 { get; set; }
        public string TO165 { get; set; }
        public Nullable<decimal> TO166 { get; set; }
        public Nullable<decimal> TO167 { get; set; }
        public Nullable<decimal> TO168 { get; set; }
        public string TO069 { get; set; }
        public string TO169 { get; set; }
        public Nullable<decimal> TO070 { get; set; }
        public Nullable<decimal> TO170 { get; set; }
        public string TO071 { get; set; }
        public string TO072 { get; set; }
        public string TO171 { get; set; }
        public string TO172 { get; set; }
        public string TO073 { get; set; }
        public string TO173 { get; set; }
        public string TO074 { get; set; }
        public string TO075 { get; set; }
        public string TO076 { get; set; }
        public string TO077 { get; set; }
        public string TO174 { get; set; }
        public string TO175 { get; set; }
        public string TO176 { get; set; }
        public string TO177 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
