//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOCTV
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TV001 { get; set; }
        public string TV002 { get; set; }
        public string TV003 { get; set; }
        public string TV004 { get; set; }
        public string TV005 { get; set; }
        public string TV006 { get; set; }
        public string TV007 { get; set; }
        public string TV008 { get; set; }
        public string TV009 { get; set; }
        public string TV010 { get; set; }
        public string TV011 { get; set; }
        public string TV012 { get; set; }
        public string TV013 { get; set; }
        public string TV014 { get; set; }
        public Nullable<decimal> TV015 { get; set; }
        public Nullable<decimal> TV016 { get; set; }
        public Nullable<decimal> TV017 { get; set; }
        public Nullable<decimal> TV018 { get; set; }
        public string TV019 { get; set; }
        public string TV020 { get; set; }
        public string TV021 { get; set; }
        public Nullable<decimal> TV022 { get; set; }
        public string TV023 { get; set; }
        public string TV024 { get; set; }
        public string TV025 { get; set; }
        public string TV026 { get; set; }
        public string TV027 { get; set; }
        public string TV028 { get; set; }
        public string TV029 { get; set; }
        public string TV030 { get; set; }
        public Nullable<decimal> TV031 { get; set; }
        public string TV032 { get; set; }
        public string TV033 { get; set; }
        public string TV034 { get; set; }
        public string TV035 { get; set; }
        public string TV036 { get; set; }
        public string TV037 { get; set; }
        public string TV038 { get; set; }
        public string TV039 { get; set; }
        public string TV040 { get; set; }
        public string TV041 { get; set; }
        public string TV042 { get; set; }
        public Nullable<decimal> TV043 { get; set; }
        public string TV044 { get; set; }
        public Nullable<decimal> TV045 { get; set; }
        public Nullable<decimal> TV046 { get; set; }
        public Nullable<decimal> TV047 { get; set; }
        public string TV048 { get; set; }
        public string TV049 { get; set; }
        public string TV050 { get; set; }
        public string TV051 { get; set; }
        public string TV052 { get; set; }
        public string TV053 { get; set; }
        public Nullable<decimal> TV054 { get; set; }
        public string TV055 { get; set; }
        public Nullable<decimal> TV056 { get; set; }
        public string TV057 { get; set; }
        public string TV058 { get; set; }
        public string TV059 { get; set; }
        public Nullable<decimal> TV060 { get; set; }
        public Nullable<decimal> TV061 { get; set; }
        public Nullable<decimal> TV062 { get; set; }
        public string TV063 { get; set; }
        public string TV064 { get; set; }
        public string TV065 { get; set; }
        public string TV066 { get; set; }
        public string TV067 { get; set; }
        public Nullable<decimal> TV068 { get; set; }
        public Nullable<decimal> TV069 { get; set; }
        public Nullable<decimal> TV070 { get; set; }
        public string TV071 { get; set; }
        public string TV072 { get; set; }
        public string TV073 { get; set; }
        public Nullable<decimal> TV074 { get; set; }
        public string TV075 { get; set; }
        public string TV076 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
