//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOCTP
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TP001 { get; set; }
        public string TP002 { get; set; }
        public string TP003 { get; set; }
        public string TP004 { get; set; }
        public Nullable<decimal> TP005 { get; set; }
        public Nullable<decimal> TP006 { get; set; }
        public string TP007 { get; set; }
        public string TP008 { get; set; }
        public string TP009 { get; set; }
        public string TP010 { get; set; }
        public string TP011 { get; set; }
        public string TP012 { get; set; }
        public string TP013 { get; set; }
        public string TP014 { get; set; }
        public string TP015 { get; set; }
        public string TP016 { get; set; }
        public string TP017 { get; set; }
        public string TP018 { get; set; }
        public string TP019 { get; set; }
        public Nullable<decimal> TP020 { get; set; }
        public Nullable<decimal> TP021 { get; set; }
        public string TP022 { get; set; }
        public string TP104 { get; set; }
        public Nullable<decimal> TP105 { get; set; }
        public Nullable<decimal> TP106 { get; set; }
        public string TP107 { get; set; }
        public string TP108 { get; set; }
        public string TP109 { get; set; }
        public string TP110 { get; set; }
        public string TP111 { get; set; }
        public string TP112 { get; set; }
        public string TP113 { get; set; }
        public string TP114 { get; set; }
        public string TP115 { get; set; }
        public string TP116 { get; set; }
        public string TP117 { get; set; }
        public string TP118 { get; set; }
        public Nullable<decimal> TP120 { get; set; }
        public Nullable<decimal> TP121 { get; set; }
        public string TP122 { get; set; }
        public string TP023 { get; set; }
        public string TP024 { get; set; }
        public string TP025 { get; set; }
        public Nullable<decimal> TP026 { get; set; }
        public Nullable<decimal> TP027 { get; set; }
        public Nullable<decimal> TP028 { get; set; }
        public string TP123 { get; set; }
        public string TP124 { get; set; }
        public string TP125 { get; set; }
        public Nullable<decimal> TP126 { get; set; }
        public Nullable<decimal> TP127 { get; set; }
        public Nullable<decimal> TP128 { get; set; }
        public string TP029 { get; set; }
        public string TP030 { get; set; }
        public string TP129 { get; set; }
        public string TP130 { get; set; }
        public string TP031 { get; set; }
        public Nullable<decimal> TP032 { get; set; }
        public string TP131 { get; set; }
        public Nullable<decimal> TP132 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
