//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOCTK
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TK001 { get; set; }
        public string TK002 { get; set; }
        public string TK003 { get; set; }
        public string TK004 { get; set; }
        public string TK005 { get; set; }
        public string TK006 { get; set; }
        public Nullable<decimal> TK007 { get; set; }
        public Nullable<decimal> TK008 { get; set; }
        public string TK009 { get; set; }
        public string TK010 { get; set; }
        public string TK011 { get; set; }
        public string TK012 { get; set; }
        public string TK013 { get; set; }
        public string TK014 { get; set; }
        public string TK015 { get; set; }
        public string TK016 { get; set; }
        public Nullable<decimal> TK017 { get; set; }
        public Nullable<decimal> TK018 { get; set; }
        public Nullable<decimal> TK019 { get; set; }
        public Nullable<decimal> TK020 { get; set; }
        public string TK021 { get; set; }
        public string TK022 { get; set; }
        public string TK023 { get; set; }
        public string TK024 { get; set; }
        public string TK025 { get; set; }
        public string TK026 { get; set; }
        public string TK027 { get; set; }
        public string TK028 { get; set; }
        public Nullable<decimal> TK029 { get; set; }
        public Nullable<decimal> TK030 { get; set; }
        public Nullable<decimal> TK031 { get; set; }
        public string TK032 { get; set; }
        public Nullable<decimal> TK033 { get; set; }
        public string TK034 { get; set; }
        public string TK035 { get; set; }
        public Nullable<decimal> TK036 { get; set; }
        public string TK037 { get; set; }
        public string TK038 { get; set; }
        public string TK039 { get; set; }
        public string TK040 { get; set; }
        public Nullable<decimal> TK041 { get; set; }
        public Nullable<decimal> TK042 { get; set; }
        public Nullable<decimal> TK043 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
