//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOCTH
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TH001 { get; set; }
        public string TH002 { get; set; }
        public string TH003 { get; set; }
        public string TH004 { get; set; }
        public string TH005 { get; set; }
        public string TH006 { get; set; }
        public string TH007 { get; set; }
        public Nullable<decimal> TH008 { get; set; }
        public Nullable<decimal> TH009 { get; set; }
        public string TH010 { get; set; }
        public string TH011 { get; set; }
        public string TH012 { get; set; }
        public string TH013 { get; set; }
        public string TH014 { get; set; }
        public string TH015 { get; set; }
        public string TH016 { get; set; }
        public string TH017 { get; set; }
        public Nullable<decimal> TH018 { get; set; }
        public Nullable<decimal> TH019 { get; set; }
        public Nullable<decimal> TH020 { get; set; }
        public Nullable<decimal> TH021 { get; set; }
        public Nullable<decimal> TH022 { get; set; }
        public string TH023 { get; set; }
        public string TH024 { get; set; }
        public Nullable<decimal> TH025 { get; set; }
        public string TH026 { get; set; }
        public Nullable<decimal> TH027 { get; set; }
        public string TH028 { get; set; }
        public string TH029 { get; set; }
        public Nullable<decimal> TH030 { get; set; }
        public Nullable<decimal> TH031 { get; set; }
        public Nullable<decimal> TH032 { get; set; }
        public string TH033 { get; set; }
        public Nullable<decimal> TH034 { get; set; }
        public string TH035 { get; set; }
        public string TH036 { get; set; }
        public Nullable<decimal> TH037 { get; set; }
        public string TH038 { get; set; }
        public string TH039 { get; set; }
        public string TH040 { get; set; }
        public string TH041 { get; set; }
        public Nullable<decimal> TH042 { get; set; }
        public Nullable<decimal> TH043 { get; set; }
        public Nullable<decimal> TH044 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
