//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOCTA
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TA001 { get; set; }
        public string TA002 { get; set; }
        public string TA003 { get; set; }
        public string TA004 { get; set; }
        public string TA005 { get; set; }
        public string TA006 { get; set; }
        public string TA007 { get; set; }
        public string TA008 { get; set; }
        public string TA009 { get; set; }
        public string TA010 { get; set; }
        public string TA011 { get; set; }
        public string TA012 { get; set; }
        public string TA013 { get; set; }
        public string TA014 { get; set; }
        public Nullable<decimal> TA015 { get; set; }
        public Nullable<decimal> TA016 { get; set; }
        public Nullable<decimal> TA017 { get; set; }
        public Nullable<decimal> TA018 { get; set; }
        public string TA019 { get; set; }
        public string TA020 { get; set; }
        public string TA021 { get; set; }
        public Nullable<decimal> TA022 { get; set; }
        public string TA023 { get; set; }
        public string TA024 { get; set; }
        public string TA025 { get; set; }
        public string TA026 { get; set; }
        public string TA027 { get; set; }
        public string TA028 { get; set; }
        public string TA029 { get; set; }
        public string TA030 { get; set; }
        public Nullable<decimal> TA031 { get; set; }
        public string TA032 { get; set; }
        public string TA033 { get; set; }
        public string TA034 { get; set; }
        public string TA035 { get; set; }
        public string TA036 { get; set; }
        public string TA037 { get; set; }
        public string TA038 { get; set; }
        public string TA039 { get; set; }
        public string TA040 { get; set; }
        public string TA041 { get; set; }
        public string TA042 { get; set; }
        public Nullable<decimal> TA043 { get; set; }
        public string TA044 { get; set; }
        public Nullable<decimal> TA045 { get; set; }
        public Nullable<decimal> TA046 { get; set; }
        public Nullable<decimal> TA047 { get; set; }
        public string TA048 { get; set; }
        public string TA049 { get; set; }
        public string TA050 { get; set; }
        public string TA051 { get; set; }
        public string TA052 { get; set; }
        public string TA053 { get; set; }
        public Nullable<decimal> TA054 { get; set; }
        public string TA055 { get; set; }
        public Nullable<decimal> TA056 { get; set; }
        public string TA057 { get; set; }
        public string TA058 { get; set; }
        public string TA059 { get; set; }
        public Nullable<decimal> TA060 { get; set; }
        public Nullable<decimal> TA061 { get; set; }
        public Nullable<decimal> TA062 { get; set; }
        public string TA063 { get; set; }
        public string TA064 { get; set; }
        public string TA065 { get; set; }
        public string TA066 { get; set; }
        public string TA067 { get; set; }
        public Nullable<decimal> TA068 { get; set; }
        public Nullable<decimal> TA069 { get; set; }
        public Nullable<decimal> TA070 { get; set; }
        public string TA071 { get; set; }
        public Nullable<decimal> TA072 { get; set; }
        public string TA073 { get; set; }
        public string TA074 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
