//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOCTU
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TU001 { get; set; }
        public string TU002 { get; set; }
        public string TU003 { get; set; }
        public string TU004 { get; set; }
        public string TU005 { get; set; }
        public string TU006 { get; set; }
        public string TU007 { get; set; }
        public string TU008 { get; set; }
        public string TU009 { get; set; }
        public string TU010 { get; set; }
        public string TU011 { get; set; }
        public string TU012 { get; set; }
        public string TU013 { get; set; }
        public string TU014 { get; set; }
        public Nullable<decimal> TU015 { get; set; }
        public Nullable<decimal> TU016 { get; set; }
        public Nullable<decimal> TU017 { get; set; }
        public Nullable<decimal> TU018 { get; set; }
        public string TU019 { get; set; }
        public string TU020 { get; set; }
        public string TU021 { get; set; }
        public Nullable<decimal> TU022 { get; set; }
        public string TU023 { get; set; }
        public string TU024 { get; set; }
        public string TU025 { get; set; }
        public string TU026 { get; set; }
        public string TU027 { get; set; }
        public string TU028 { get; set; }
        public string TU029 { get; set; }
        public string TU030 { get; set; }
        public Nullable<decimal> TU031 { get; set; }
        public string TU032 { get; set; }
        public string TU033 { get; set; }
        public string TU034 { get; set; }
        public string TU035 { get; set; }
        public string TU036 { get; set; }
        public string TU037 { get; set; }
        public string TU038 { get; set; }
        public string TU039 { get; set; }
        public string TU040 { get; set; }
        public string TU041 { get; set; }
        public string TU042 { get; set; }
        public Nullable<decimal> TU043 { get; set; }
        public string TU044 { get; set; }
        public Nullable<decimal> TU045 { get; set; }
        public Nullable<decimal> TU046 { get; set; }
        public Nullable<decimal> TU047 { get; set; }
        public string TU048 { get; set; }
        public string TU049 { get; set; }
        public string TU050 { get; set; }
        public string TU051 { get; set; }
        public string TU052 { get; set; }
        public string TU053 { get; set; }
        public Nullable<decimal> TU054 { get; set; }
        public string TU055 { get; set; }
        public Nullable<decimal> TU056 { get; set; }
        public string TU057 { get; set; }
        public string TU058 { get; set; }
        public string TU059 { get; set; }
        public Nullable<decimal> TU060 { get; set; }
        public Nullable<decimal> TU061 { get; set; }
        public Nullable<decimal> TU062 { get; set; }
        public string TU063 { get; set; }
        public string TU064 { get; set; }
        public string TU065 { get; set; }
        public string TU066 { get; set; }
        public string TU067 { get; set; }
        public Nullable<decimal> TU068 { get; set; }
        public Nullable<decimal> TU069 { get; set; }
        public Nullable<decimal> TU070 { get; set; }
        public string TU071 { get; set; }
        public string TU072 { get; set; }
        public Nullable<decimal> TU073 { get; set; }
        public string TU074 { get; set; }
        public string TU075 { get; set; }
        public string TU076 { get; set; }
        public string TU077 { get; set; }
        public string TU078 { get; set; }
        public string TU079 { get; set; }
        public string TU080 { get; set; }
        public Nullable<decimal> TU081 { get; set; }
        public string TU082 { get; set; }
        public string TU083 { get; set; }
        public string TU084 { get; set; }
        public string TU085 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
