//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOCTS
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TS001 { get; set; }
        public string TS002 { get; set; }
        public string TS003 { get; set; }
        public string TS004 { get; set; }
        public string TS005 { get; set; }
        public string TS006 { get; set; }
        public string TS007 { get; set; }
        public string TS008 { get; set; }
        public string TS009 { get; set; }
        public Nullable<decimal> TS010 { get; set; }
        public string TS011 { get; set; }
        public string TS012 { get; set; }
        public string TS013 { get; set; }
        public string TS014 { get; set; }
        public Nullable<decimal> TS015 { get; set; }
        public string TS016 { get; set; }
        public string TS017 { get; set; }
        public string TS018 { get; set; }
        public string TS019 { get; set; }
        public string TS020 { get; set; }
        public string TS021 { get; set; }
        public string TS022 { get; set; }
        public string TS023 { get; set; }
        public string TS024 { get; set; }
        public Nullable<decimal> TS025 { get; set; }
        public Nullable<decimal> TS026 { get; set; }
        public Nullable<decimal> TS027 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
