//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODEL_ST
    {
        public string MODEL { get; set; }
        public Nullable<double> ST { get; set; }
        public Nullable<double> SUB_ST { get; set; }
    }
}
