//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelBOM
    {
        public string mc001 { get; set; }
        public string mc010 { get; set; }
        public string mb002 { get; set; }
        public string mb180 { get; set; }
        public string mb025 { get; set; }
    }
}
