//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPSTB
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TB001 { get; set; }
        public string TB002 { get; set; }
        public string TB003 { get; set; }
        public string TB004 { get; set; }
        public string TB005 { get; set; }
        public string TB006 { get; set; }
        public Nullable<decimal> TB007 { get; set; }
        public Nullable<decimal> TB008 { get; set; }
        public string TB009 { get; set; }
        public string TB010 { get; set; }
        public string TB011 { get; set; }
        public string TB012 { get; set; }
        public string TB013 { get; set; }
        public string TB014 { get; set; }
        public Nullable<decimal> TB015 { get; set; }
        public Nullable<decimal> TB016 { get; set; }
        public Nullable<decimal> TB017 { get; set; }
        public Nullable<decimal> TB018 { get; set; }
        public Nullable<decimal> TB019 { get; set; }
        public Nullable<decimal> TB020 { get; set; }
        public Nullable<decimal> TB021 { get; set; }
        public Nullable<decimal> TB022 { get; set; }
        public Nullable<decimal> TB023 { get; set; }
        public Nullable<decimal> TB024 { get; set; }
        public Nullable<decimal> TB025 { get; set; }
        public Nullable<decimal> TB026 { get; set; }
        public string TB027 { get; set; }
        public string TB028 { get; set; }
        public Nullable<decimal> TB029 { get; set; }
        public Nullable<decimal> TB030 { get; set; }
        public Nullable<decimal> TB031 { get; set; }
        public Nullable<decimal> TB032 { get; set; }
        public string TB033 { get; set; }
        public string TB034 { get; set; }
        public string TB035 { get; set; }
        public string TB036 { get; set; }
        public string TB037 { get; set; }
        public string TB038 { get; set; }
        public Nullable<decimal> TB039 { get; set; }
        public string TB040 { get; set; }
        public string TB041 { get; set; }
        public string TB042 { get; set; }
        public Nullable<decimal> TB043 { get; set; }
        public string TB044 { get; set; }
        public string TB045 { get; set; }
        public string TB046 { get; set; }
        public Nullable<decimal> TB047 { get; set; }
        public Nullable<decimal> TB048 { get; set; }
        public string TB049 { get; set; }
        public string TB050 { get; set; }
        public string TB051 { get; set; }
        public string TB052 { get; set; }
        public string TB053 { get; set; }
        public string TB054 { get; set; }
        public Nullable<decimal> TB055 { get; set; }
        public Nullable<decimal> TB056 { get; set; }
        public Nullable<decimal> TB057 { get; set; }
        public string TB058 { get; set; }
        public string TB059 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
