//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTTF
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TF001 { get; set; }
        public string TF002 { get; set; }
        public string TF003 { get; set; }
        public string TF004 { get; set; }
        public string TF005 { get; set; }
        public Nullable<decimal> TF006 { get; set; }
        public string TF007 { get; set; }
        public string TF008 { get; set; }
        public string TF009 { get; set; }
        public string TF010 { get; set; }
        public string TF011 { get; set; }
        public string TF012 { get; set; }
        public Nullable<decimal> TF013 { get; set; }
        public Nullable<decimal> TF014 { get; set; }
        public Nullable<decimal> TF015 { get; set; }
        public string TF016 { get; set; }
        public string TF017 { get; set; }
        public string TF018 { get; set; }
        public Nullable<decimal> TF019 { get; set; }
        public string TF020 { get; set; }
        public string TF021 { get; set; }
        public string TF022 { get; set; }
        public string TF023 { get; set; }
        public string TF024 { get; set; }
        public string TF025 { get; set; }
        public Nullable<decimal> TF026 { get; set; }
        public Nullable<decimal> TF027 { get; set; }
        public Nullable<decimal> TF028 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
