//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWE
    {
        public string PartsNo { get; set; }
        public string Description { get; set; }
        public string MainSupplier { get; set; }
        public string MainSupplierShort { get; set; }
        public Nullable<decimal> DTAStock { get; set; }
        public Nullable<decimal> TACStock { get; set; }
        public string JobNo { get; set; }
        public string Purchaser { get; set; }
        public Nullable<decimal> Material { get; set; }
        public Nullable<decimal> Scrap { get; set; }
        public Nullable<decimal> IQC { get; set; }
        public Nullable<decimal> Material2 { get; set; }
        public Nullable<decimal> Defective { get; set; }
        public Nullable<decimal> SMT { get; set; }
        public Nullable<decimal> ManualInsertion { get; set; }
        public Nullable<decimal> Assemble { get; set; }
        public string D { get; set; }
        public string No { get; set; }
        public string LotUse { get; set; }
        public Nullable<decimal> Requisite { get; set; }
        public Nullable<decimal> Received { get; set; }
        public Nullable<decimal> Residual { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierShort { get; set; }
        public string PoNo { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Delivered { get; set; }
        public Nullable<decimal> Nondelivery { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public string DTAPoNo { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<decimal> Inspect { get; set; }
    }
}
