//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PALMJ
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public decimal MJ001 { get; set; }
        public Nullable<decimal> MJ002 { get; set; }
        public Nullable<decimal> MJ003 { get; set; }
        public Nullable<decimal> MJ004 { get; set; }
        public Nullable<decimal> MJ005 { get; set; }
        public Nullable<decimal> MJ006 { get; set; }
        public Nullable<decimal> MJ007 { get; set; }
        public Nullable<decimal> MJ008 { get; set; }
        public Nullable<decimal> MJ009 { get; set; }
        public Nullable<decimal> MJ010 { get; set; }
        public Nullable<decimal> MJ011 { get; set; }
        public Nullable<decimal> MJ012 { get; set; }
        public Nullable<decimal> MJ013 { get; set; }
        public string MJ014 { get; set; }
        public string MJ015 { get; set; }
        public string MJ016 { get; set; }
        public Nullable<decimal> MJ017 { get; set; }
        public Nullable<decimal> MJ018 { get; set; }
        public Nullable<decimal> MJ019 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
