//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PALMK
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MK001 { get; set; }
        public string MK002 { get; set; }
        public string MK003 { get; set; }
        public string MK004 { get; set; }
        public string MK005 { get; set; }
        public string MK006 { get; set; }
        public string MK007 { get; set; }
        public string MK008 { get; set; }
        public string MK009 { get; set; }
        public string MK010 { get; set; }
        public string MK011 { get; set; }
        public string MK012 { get; set; }
        public Nullable<decimal> MK013 { get; set; }
        public Nullable<decimal> MK014 { get; set; }
        public Nullable<decimal> MK015 { get; set; }
        public Nullable<decimal> MK016 { get; set; }
        public Nullable<decimal> MK017 { get; set; }
        public Nullable<decimal> MK018 { get; set; }
        public string MK019 { get; set; }
        public Nullable<decimal> MK020 { get; set; }
        public string MK021 { get; set; }
        public string MK022 { get; set; }
        public string MK023 { get; set; }
        public Nullable<decimal> MK024 { get; set; }
        public Nullable<decimal> MK025 { get; set; }
        public Nullable<decimal> MK026 { get; set; }
        public string MK027 { get; set; }
        public string MK028 { get; set; }
        public string MK029 { get; set; }
        public string MK030 { get; set; }
        public string MK031 { get; set; }
        public string MK032 { get; set; }
        public string MK033 { get; set; }
        public string MK034 { get; set; }
        public string MK035 { get; set; }
        public string MK036 { get; set; }
        public string MK037 { get; set; }
        public string MK038 { get; set; }
        public string MK039 { get; set; }
        public string MK040 { get; set; }
        public string MK041 { get; set; }
        public string MK042 { get; set; }
        public string MK043 { get; set; }
        public string MK044 { get; set; }
        public string MK045 { get; set; }
        public string MK046 { get; set; }
        public string MK047 { get; set; }
        public string MK048 { get; set; }
        public string MK049 { get; set; }
        public string MK050 { get; set; }
        public string MK051 { get; set; }
        public string MK052 { get; set; }
        public string MK053 { get; set; }
        public string MK054 { get; set; }
        public string MK055 { get; set; }
        public string MK056 { get; set; }
        public string MK057 { get; set; }
        public string MK058 { get; set; }
        public string MK059 { get; set; }
        public Nullable<decimal> MK060 { get; set; }
        public Nullable<decimal> MK061 { get; set; }
        public Nullable<decimal> MK062 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
