//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PALNF
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string NF001 { get; set; }
        public string NF002 { get; set; }
        public string NF003 { get; set; }
        public string NF004 { get; set; }
        public string NF005 { get; set; }
        public string NF006 { get; set; }
        public string NF007 { get; set; }
        public Nullable<decimal> NF008 { get; set; }
        public string NF009 { get; set; }
        public string NF010 { get; set; }
        public string NF011 { get; set; }
        public string NF012 { get; set; }
        public string NF013 { get; set; }
        public string NF014 { get; set; }
        public string NF015 { get; set; }
        public string NF016 { get; set; }
        public string NF017 { get; set; }
        public string NF018 { get; set; }
        public string NF019 { get; set; }
        public string NF020 { get; set; }
        public Nullable<decimal> NF021 { get; set; }
        public Nullable<decimal> NF022 { get; set; }
        public Nullable<decimal> NF023 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
