//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PALTQ
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TQ001 { get; set; }
        public string TQ002 { get; set; }
        public string TQ003 { get; set; }
        public string TQ004 { get; set; }
        public string TQ005 { get; set; }
        public string TQ006 { get; set; }
        public string TQ007 { get; set; }
        public string TQ008 { get; set; }
        public string TQ009 { get; set; }
        public string TQ010 { get; set; }
        public string TQ011 { get; set; }
        public string TQ012 { get; set; }
        public string TQ013 { get; set; }
        public string TQ014 { get; set; }
        public Nullable<decimal> TQ015 { get; set; }
        public Nullable<decimal> TQ016 { get; set; }
        public Nullable<decimal> TQ017 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
