//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURLC
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string LC001 { get; set; }
        public string LC002 { get; set; }
        public Nullable<decimal> LC003 { get; set; }
        public Nullable<decimal> LC004 { get; set; }
        public Nullable<decimal> LC005 { get; set; }
        public Nullable<decimal> LC006 { get; set; }
        public Nullable<decimal> LC007 { get; set; }
        public Nullable<decimal> LC008 { get; set; }
        public Nullable<decimal> LC009 { get; set; }
        public Nullable<decimal> LC010 { get; set; }
        public Nullable<decimal> LC011 { get; set; }
        public Nullable<decimal> LC012 { get; set; }
        public Nullable<decimal> LC013 { get; set; }
        public Nullable<decimal> LC014 { get; set; }
        public Nullable<decimal> LC015 { get; set; }
        public string LC016 { get; set; }
        public string LC017 { get; set; }
        public string LC018 { get; set; }
        public Nullable<decimal> LC019 { get; set; }
        public Nullable<decimal> LC020 { get; set; }
        public Nullable<decimal> LC021 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
