//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURTH
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TH001 { get; set; }
        public string TH002 { get; set; }
        public string TH003 { get; set; }
        public string TH004 { get; set; }
        public string TH005 { get; set; }
        public string TH006 { get; set; }
        public Nullable<decimal> TH007 { get; set; }
        public string TH008 { get; set; }
        public string TH009 { get; set; }
        public string TH010 { get; set; }
        public string TH011 { get; set; }
        public string TH012 { get; set; }
        public string TH013 { get; set; }
        public string TH014 { get; set; }
        public Nullable<decimal> TH015 { get; set; }
        public Nullable<decimal> TH016 { get; set; }
        public Nullable<decimal> TH017 { get; set; }
        public Nullable<decimal> TH018 { get; set; }
        public Nullable<decimal> TH019 { get; set; }
        public Nullable<decimal> TH020 { get; set; }
        public string TH021 { get; set; }
        public string TH022 { get; set; }
        public string TH023 { get; set; }
        public Nullable<decimal> TH024 { get; set; }
        public string TH025 { get; set; }
        public string TH026 { get; set; }
        public string TH027 { get; set; }
        public string TH028 { get; set; }
        public string TH029 { get; set; }
        public string TH030 { get; set; }
        public string TH031 { get; set; }
        public string TH032 { get; set; }
        public string TH033 { get; set; }
        public Nullable<decimal> TH034 { get; set; }
        public string TH035 { get; set; }
        public string TH036 { get; set; }
        public string TH037 { get; set; }
        public string TH038 { get; set; }
        public string TH039 { get; set; }
        public string TH040 { get; set; }
        public string TH041 { get; set; }
        public string TH042 { get; set; }
        public string TH043 { get; set; }
        public string TH044 { get; set; }
        public Nullable<decimal> TH045 { get; set; }
        public Nullable<decimal> TH046 { get; set; }
        public Nullable<decimal> TH047 { get; set; }
        public Nullable<decimal> TH048 { get; set; }
        public Nullable<decimal> TH049 { get; set; }
        public Nullable<decimal> TH050 { get; set; }
        public Nullable<decimal> TH051 { get; set; }
        public Nullable<decimal> TH052 { get; set; }
        public string TH053 { get; set; }
        public Nullable<decimal> TH054 { get; set; }
        public Nullable<decimal> TH055 { get; set; }
        public string TH056 { get; set; }
        public string TH057 { get; set; }
        public Nullable<decimal> TH058 { get; set; }
        public Nullable<decimal> TH059 { get; set; }
        public Nullable<decimal> TH060 { get; set; }
        public Nullable<decimal> TH061 { get; set; }
        public Nullable<decimal> TH062 { get; set; }
        public string TH063 { get; set; }
        public string TH064 { get; set; }
        public string TH065 { get; set; }
        public string TH066 { get; set; }
        public string TH067 { get; set; }
        public Nullable<decimal> TH068 { get; set; }
        public Nullable<decimal> TH069 { get; set; }
        public string TH070 { get; set; }
        public Nullable<decimal> TH071 { get; set; }
        public string TH072 { get; set; }
        public string TH073 { get; set; }
        public string TH074 { get; set; }
        public string TH075 { get; set; }
        public string TH076 { get; set; }
        public Nullable<decimal> TH077 { get; set; }
        public Nullable<decimal> TH078 { get; set; }
        public Nullable<decimal> TH079 { get; set; }
        public string TH080 { get; set; }
        public string TH200 { get; set; }
        public string TH201 { get; set; }
        public string TH202 { get; set; }
        public Nullable<decimal> TH203 { get; set; }
        public Nullable<decimal> TH204 { get; set; }
        public Nullable<decimal> TH205 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
