//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURTF
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TF001 { get; set; }
        public string TF002 { get; set; }
        public string TF003 { get; set; }
        public string TF004 { get; set; }
        public string TF005 { get; set; }
        public string TF006 { get; set; }
        public string TF007 { get; set; }
        public string TF008 { get; set; }
        public Nullable<decimal> TF009 { get; set; }
        public string TF010 { get; set; }
        public Nullable<decimal> TF011 { get; set; }
        public Nullable<decimal> TF012 { get; set; }
        public string TF013 { get; set; }
        public string TF014 { get; set; }
        public Nullable<decimal> TF015 { get; set; }
        public string TF016 { get; set; }
        public string TF017 { get; set; }
        public Nullable<decimal> TF018 { get; set; }
        public string TF019 { get; set; }
        public string TF020 { get; set; }
        public string TF021 { get; set; }
        public string TF022 { get; set; }
        public string TF023 { get; set; }
        public Nullable<decimal> TF024 { get; set; }
        public string TF025 { get; set; }
        public string TF104 { get; set; }
        public string TF105 { get; set; }
        public string TF106 { get; set; }
        public string TF107 { get; set; }
        public string TF108 { get; set; }
        public Nullable<decimal> TF109 { get; set; }
        public string TF110 { get; set; }
        public Nullable<decimal> TF111 { get; set; }
        public Nullable<decimal> TF112 { get; set; }
        public string TF113 { get; set; }
        public string TF114 { get; set; }
        public Nullable<decimal> TF118 { get; set; }
        public string TF119 { get; set; }
        public string TF120 { get; set; }
        public string TF121 { get; set; }
        public string TF122 { get; set; }
        public string TF123 { get; set; }
        public Nullable<decimal> TF124 { get; set; }
        public Nullable<decimal> TF125 { get; set; }
        public string TF126 { get; set; }
        public Nullable<decimal> TF026 { get; set; }
        public Nullable<decimal> TF027 { get; set; }
        public Nullable<decimal> TF028 { get; set; }
        public Nullable<decimal> TF127 { get; set; }
        public Nullable<decimal> TF128 { get; set; }
        public Nullable<decimal> TF129 { get; set; }
        public string TF029 { get; set; }
        public string TF130 { get; set; }
        public string TF030 { get; set; }
        public string TF131 { get; set; }
        public string TF031 { get; set; }
        public Nullable<decimal> TF032 { get; set; }
        public string TF132 { get; set; }
        public Nullable<decimal> TF133 { get; set; }
        public string TF033 { get; set; }
        public string TF134 { get; set; }
        public string TF034 { get; set; }
        public string TF035 { get; set; }
        public string TF036 { get; set; }
        public Nullable<decimal> TF037 { get; set; }
        public Nullable<decimal> TF038 { get; set; }
        public Nullable<decimal> TF039 { get; set; }
        public string TF135 { get; set; }
        public string TF136 { get; set; }
        public string TF137 { get; set; }
        public Nullable<decimal> TF138 { get; set; }
        public Nullable<decimal> TF139 { get; set; }
        public Nullable<decimal> TF140 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
