//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMATG
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TG001 { get; set; }
        public string TG002 { get; set; }
        public string TG003 { get; set; }
        public string TG004 { get; set; }
        public string TG005 { get; set; }
        public string TG006 { get; set; }
        public string TG007 { get; set; }
        public string TG008 { get; set; }
        public string TG009 { get; set; }
        public string TG010 { get; set; }
        public string TG011 { get; set; }
        public Nullable<decimal> TG012 { get; set; }
        public string TG013 { get; set; }
        public Nullable<decimal> TG014 { get; set; }
        public string TG015 { get; set; }
        public string TG016 { get; set; }
        public string TG017 { get; set; }
        public string TG018 { get; set; }
        public string TG019 { get; set; }
        public string TG020 { get; set; }
        public string TG021 { get; set; }
        public Nullable<decimal> TG022 { get; set; }
        public Nullable<decimal> TG023 { get; set; }
        public Nullable<decimal> TG024 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
