//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeanFine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sourcetable
    {
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFIER { get; set; }
        public string MODI_DATE { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TD001 { get; set; }
        public string TD002 { get; set; }
        public string TD003 { get; set; }
        public string TD004 { get; set; }
        public string TD005 { get; set; }
        public string TD006 { get; set; }
        public string TD007 { get; set; }
        public Nullable<decimal> TD008 { get; set; }
        public string TD009 { get; set; }
        public Nullable<decimal> TD010 { get; set; }
        public Nullable<decimal> TD011 { get; set; }
        public string TD012 { get; set; }
        public string TD013 { get; set; }
        public string TD014 { get; set; }
        public Nullable<decimal> TD015 { get; set; }
        public string TD016 { get; set; }
        public string TD017 { get; set; }
        public string TD018 { get; set; }
        public Nullable<decimal> TD019 { get; set; }
        public string TD020 { get; set; }
        public string TD021 { get; set; }
        public string TD022 { get; set; }
        public string TD023 { get; set; }
        public string TD024 { get; set; }
        public string TD025 { get; set; }
        public string TD026 { get; set; }
        public string TD027 { get; set; }
        public string TD028 { get; set; }
        public string TD029 { get; set; }
        public Nullable<decimal> TD030 { get; set; }
        public Nullable<decimal> TD031 { get; set; }
        public string TD032 { get; set; }
        public Nullable<decimal> TD033 { get; set; }
        public Nullable<decimal> TD034 { get; set; }
        public Nullable<decimal> TD035 { get; set; }
        public Nullable<decimal> TD036 { get; set; }
        public Nullable<decimal> TD037 { get; set; }
        public string TD038 { get; set; }
        public Nullable<decimal> TD039 { get; set; }
        public string TD040 { get; set; }
        public string TD041 { get; set; }
        public string TD042 { get; set; }
        public string TD043 { get; set; }
        public string TD044 { get; set; }
        public Nullable<decimal> TD045 { get; set; }
        public Nullable<decimal> TD046 { get; set; }
        public Nullable<decimal> TD047 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public Nullable<decimal> UDF51 { get; set; }
        public Nullable<decimal> UDF52 { get; set; }
        public Nullable<decimal> UDF53 { get; set; }
        public Nullable<decimal> UDF54 { get; set; }
        public Nullable<decimal> UDF55 { get; set; }
        public Nullable<decimal> UDF56 { get; set; }
    }
}
