//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_User
    {
        public int UserID { get; set; }
        public string U_LoginName { get; set; }
        public string U_Password { get; set; }
        public string U_CName { get; set; }
        public string U_EName { get; set; }
        public int U_GroupID { get; set; }
        public string U_Email { get; set; }
        public byte U_Type { get; set; }
        public byte U_Status { get; set; }
        public string U_Licence { get; set; }
        public string U_Mac { get; set; }
        public string U_Remark { get; set; }
        public string U_IDCard { get; set; }
        public Nullable<byte> U_Sex { get; set; }
        public Nullable<System.DateTime> U_BirthDay { get; set; }
        public string U_MobileNo { get; set; }
        public string U_UserNO { get; set; }
        public Nullable<System.DateTime> U_WorkStartDate { get; set; }
        public Nullable<System.DateTime> U_WorkEndDate { get; set; }
        public string U_CompanyMail { get; set; }
        public Nullable<int> U_Title { get; set; }
        public string U_Extension { get; set; }
        public string U_HomeTel { get; set; }
        public string U_PhotoUrl { get; set; }
        public Nullable<System.DateTime> U_DateTime { get; set; }
        public string U_LastIP { get; set; }
        public Nullable<System.DateTime> U_LastDateTime { get; set; }
        public string U_ExtendField { get; set; }
    }
}
