//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Event
    {
        public int EventID { get; set; }
        public string E_U_LoginName { get; set; }
        public Nullable<int> E_UserID { get; set; }
        public System.DateTime E_DateTime { get; set; }
        public Nullable<int> E_ApplicationID { get; set; }
        public string E_A_AppName { get; set; }
        public string E_M_Name { get; set; }
        public string E_M_PageCode { get; set; }
        public string E_From { get; set; }
        public byte E_Type { get; set; }
        public string E_IP { get; set; }
        public string E_Record { get; set; }
    }
}
