//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_SystemInfo
    {
        public int SystemID { get; set; }
        public string S_Name { get; set; }
        public string S_Version { get; set; }
        public byte[] S_SystemConfigData { get; set; }
        public string S_Licensed { get; set; }
    }
}
