//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Module
    {
        public int ModuleID { get; set; }
        public int M_ApplicationID { get; set; }
        public int M_ParentID { get; set; }
        public string M_PageCode { get; set; }
        public string M_CName { get; set; }
        public string M_Directory { get; set; }
        public string M_OrderLevel { get; set; }
        public Nullable<byte> M_IsSystem { get; set; }
        public Nullable<byte> M_Close { get; set; }
        public string M_Icon { get; set; }
    }
}
