//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lean.Fineform.Lf_Business.Models.YF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_FieldValue
    {
        public int ValueID { get; set; }
        public string V_F_Key { get; set; }
        public string V_Text { get; set; }
        public int V_ShowOrder { get; set; }
    }
}
